[package]
name = "odonate"
version = "0.1.0"
authors = ["Andy Watkins", "Hector"]
edition = "2018"
description = """
Chess
"""
repository = "https://github.com/akanalytics/odonate"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.2"
# arrayvec = "0.5"
# lazy_static = "1.4"
once_cell = "1.7"
regex = "1.4"
log = { version = "0.4", features = ["release_max_level_off"] }

[dev-dependencies]
criterion = "0.3"
env_logger = "0.8" 


[[bench]]
name = "benchmark"
harness = false




