[package]
name = "odonata"
version = "0.6.18"
license = "GPL-3.0+"
homepage = "https://github.com/akanalytics/odonata"
authors = [
    "andy watkins <andy@webcalculator.com>",
    "mark raistrick <mark.raistrick@gmail.com>",
]
edition = "2021"
description = """
A simple UCI compliant chess engine
"""
keywords = ["chess"]
repository = "https://github.com/akanalytics/odonata"

# for built dependency
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
test-log = "0.2"
clap = "3.1.18"
bitflags = "1.2"
arrayvec = "0.7"
once_cell = "1.7"
regex = "1.4"
rand = "0.8"
rand_chacha = "0.3"
env_logger = "0.9"
log = { version = "0.4", features = ["release_max_level_debug"] }
crossbeam-utils = "0.8.8" #{ git = "https://github.com/crossbeam-rs/crossbeam" }
static_init = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = "1.9"
jsonrpc-core = "17.1"
jsonrpc-derive = "17.1"
strum = "0.24"
strum_macros = "0.24"
format_num = "0.1"
itertools = "0.10"
rayon = "1.5"
num-traits = "0.2"
include_dir = "0.7.2"
enumflags2 = { version = "0.7", features = ["serde"] }
anyhow = { version = "1.0", features = ["backtrace"] }
figment = { version = "0.10.6", features = ["env", "toml", "test"] }
toml = "0.5.8"
petgraph = "0.6.0"
backtrace = "0.3.64"
thread_local = "1.1.4"
tabled = "0.8.0"
# tabled = { git = "https://github.com/zhiburt/tabled", branch = "master" }
hdrhist = "0.5.0"
csv = "1.1.6"
chrono = { version = "0.4" }
fslock = "0.2.1"
perf-event = "0.4.7"



[dev-dependencies]
criterion = "0.3"


[build-dependencies]
built = { version = "0.5", features = ["chrono", "semver"] }
include_dir = "0.6"


[[bench]]
name = "benchmark"
harness = false


[profile.bench]
debug = true
opt-level = 3
incremental = true
codegen-units = 256
# lto = true

[profile.dev]
opt-level = 3
incremental = true
debug = true  # allow profiling of the  main executable 
split-debuginfo = "unpacked"
codegen-units = 256

[profile.test]
opt-level = 2
incremental = true
debug = true  # allow profiling of the  main executable 
codegen-units = 256
split-debuginfo = "off"  # for hotspot profiler disassembly

[profile.release]
opt-level = 3
incremental = false
codegen-units = 256
debug = true  # allow profiling of the  main executable 
split-debuginfo = "unpacked"

[profile.tournament]
#panic = "abort"
inherits = "release"
opt-level = 3
incremental = true
codegen-units = 1
debug = false
split-debuginfo = "unpacked"

[profile.stable]
inherits = "tournament"
split-debuginfo = "unpacked"

[lib]
# bug in criterion<->cargo interaction https://bheisler.github.io/criterion.rs/book/faq.html
bench = false

[[bin]]
name = "odonata"
bench = false

[features]
remove_metrics = []
unchecked_indexing = []
remove_logging = []
fast = ["remove_logging", "unchecked_indexing", "remove_metrics"]

# RUSTFLAGS="-C target-cpu=native" cargo bench

# in .cargo/config.toml
# rustflags = ["-C target-cpu=native"]

# rustc --print cfg
# rustc -C target-cpu=native --print cfg
