[package]
name = "odonata"
version = "0.3.6"
homepage = "https://github.com/akanalytics/odonata"
authors = ["andy watkins"]
edition = "2018"
description = """
Chess
"""
repository = "https://github.com/akanalytics/odonata"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.2"
# arrayvec = "0.5"
# lazy_static = "1.4"
once_cell = "1.7"
regex = "1.4"
rand = "0.8.3"
rand_chacha = "0.3.0"
env_logger = "0.8" 
log = { version = "0.4", features = ["release_max_level_off"] }

[dev-dependencies]
criterion = "0.3"


[[bench]]
name = "benchmark"
harness = false

[profile.release]
debug = true


