[package]
name = "odonata"
version = "0.5.12"
license = "GPL-3.0+"
homepage = "https://github.com/akanalytics/odonata"
authors = [
    "andy watkins <andy@webcalculator.com>",
    "mark raistrick <mark.raistrick@gmail.com>",
]
edition = "2018"
description = """
A simple UCI compliant chess engine
"""
keywords = ["chess"]
repository = "https://github.com/akanalytics/odonata"

# for built dependency
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
test-log = "0.2"
clap = "2.33"
bitflags = "1.2"
arrayvec = "0.7"
once_cell = "1.7"
regex = "1.4"
rand = "0.8"
rand_chacha = "0.3"
env_logger = "0.8"
log = { version = "0.4", features = ["release_max_level_debug"] }
# lazy_static = "1.4"
# crossbeam = "0.8"
# ctor = "0.1"
static_init = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = "1.9"
jsonrpc-core = "17.1"
jsonrpc-derive = "17.1"
strum = "0.21"
strum_macros = "0.21"
format_num = "0.1"
itertools = "0.10"
rayon = "1.5"
num-traits = "0.2"
include_dir = "0.6"
enumflags2 = { version = "0.7", features = ["serde"] }
tracing = "0.1"
tracing-subscriber = "0.2"                         # = { version="0.2", features=["fmt", "env-filter", "ansi", "registry"]}
# tracing-log = "0.1"
anyhow = "1.0"
figment = { version = "0.10.6", features = ["env", "toml", "test"] }
toml = "0.5.8"
tabwriter = "1.2.1"


[dev-dependencies]
criterion = "0.3"
iai = "0.1"
# criterion-linux-perf = "0.1" # https://crates.io/crates/criterion-linux-perf


[build-dependencies]
built = { version = "0.5", features = ["chrono", "semver"] }
chrono = { version = "0.4", optional = true, default-features = false, features = [
    "clock",
] }
include_dir = "0.6"


[[bench]]
name = "iai"
harness = false

[[bench]]
name = "benchmark"
harness = false


[profile.bench]
debug = true
opt-level = 3
incremental = true
codegen-units = 256
# lto = true

[profile.dev]
opt-level = 3
debug = true  # allow profiling of the  main executable 

[profile.test]
opt-level = 3
debug = true  # allow profiling of the  main executable 

[profile.release]
lto = false
opt-level = 3
incremental = false
codegen-units = 1
debug = true  # allow profiling of the  main executable 

[profile.tournament]
#panic = "abort"
inherits = "release"
lto = true
opt-level = 3
incremental = false
codegen-units = 1

[profile.stable]
inherits = "tournament"

[lib]
# bug in criterion<->cargo interaction https://bheisler.github.io/criterion.rs/book/faq.html
bench = false

[[bin]]
name = "odonata"
bench = false

[features]
remove_metrics = []
unchecked_indexing = []
remove_logging = []
fast = ["remove_logging", "unchecked_indexing", "remove_metrics"]

# RUSTFLAGS="-C target-cpu=native" cargo bench

# in .cargo/config.toml
# rustflags = ["-C target-cpu=native"]

# rustc --print cfg
# rustc -C target-cpu=native --print cfg
