[package]
name = "odonata"
version = "0.5.61"
license = "GPL-3.0+"
homepage = "https://github.com/akanalytics/odonata"
authors = [
    "andy watkins <andy@webcalculator.com>",
    "mark raistrick <mark.raistrick@gmail.com>",
]
edition = "2021"
description = """
A simple UCI compliant chess engine
"""
keywords = ["chess"]
repository = "https://github.com/akanalytics/odonata"

# for built dependency
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
test-log = "0.2"
clap = "2.33"
bitflags = "1.2"
arrayvec = "0.7"
once_cell = "1.7"
regex = "1.4"
rand = "0.8"
rand_chacha = "0.3"
env_logger = "0.8"
log = { version = "0.4", features = ["release_max_level_debug"] }
# lazy_static = "1.4"
crossbeam-utils = "0.8.8" #{ git = "https://github.com/crossbeam-rs/crossbeam" }
# ctor = "0.1"
static_init = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = "1.9"
jsonrpc-core = "17.1"
jsonrpc-derive = "17.1"
strum = "0.21"
strum_macros = "0.21"
format_num = "0.1"
itertools = "0.10"
rayon = "1.5"
num-traits = "0.2"
include_dir = "0.6"
enumflags2 = { version = "0.7", features = ["serde"] }
tracing = "0.1"
tracing-subscriber = "0.2"                         # = { version="0.2", features=["fmt", "env-filter", "ansi", "registry"]}
# tracing-log = "0.1"
anyhow = { version = "1.0", features = ["backtrace"] }
figment = { version = "0.10.6", features = ["env", "toml", "test"] }
toml = "0.5.8"
tabwriter = "1.2.1"
# rose_tree = "0.3.0"
petgraph = "0.6.0"
backtrace = "0.3.64"
# firestorm = "0.5.0"
fast-math = "0.1.1"
thread_local = "1.1.4"
# firestorm = { version="0.5", features=["enable_system_time"] }
# firestorm = { version="0.5", features=["enable_cpu_time"] }
# hprof = "0.1.3"
tabled = "0.7.0"
hdrhist = "0.5.0"

[dev-dependencies]
criterion = "0.3"
# criterion-linux-perf = "0.1" # https://crates.io/crates/criterion-linux-perf
perf-event = "0.4.7"
# firestorm = { version="0.5", features=["enable_system_time"] }


[build-dependencies]
built = { version = "0.5", features = ["chrono", "semver"] }
chrono = { version = "0.4", optional = true, default-features = false, features = [
    "clock",
] }
include_dir = "0.6"


[[bench]]
name = "benchmark"
harness = false


[profile.bench]
debug = true
opt-level = 3
incremental = true
codegen-units = 256
# lto = true

[profile.dev]
opt-level = 3
incremental = true
debug = true  # allow profiling of the  main executable 
split-debuginfo = "unpacked"
codegen-units = 256

[profile.test]
opt-level = 3
incremental = false
debug = true  # allow profiling of the  main executable 
codegen-units = 256
split-debuginfo = "off"  # for hotspot profiler disassembly

[profile.release]
opt-level = 3
incremental = false
codegen-units = 256
debug = true  # allow profiling of the  main executable 
split-debuginfo = "unpacked"

[profile.tournament]
#panic = "abort"
inherits = "release"
opt-level = 3
incremental = true
codegen-units = 1
debug = false
split-debuginfo = "unpacked"

[profile.stable]
inherits = "tournament"
split-debuginfo = "unpacked"

[lib]
# bug in criterion<->cargo interaction https://bheisler.github.io/criterion.rs/book/faq.html
bench = false

[[bin]]
name = "odonata"
bench = false

[features]
remove_metrics = []
unchecked_indexing = []
remove_logging = []
fast = ["remove_logging", "unchecked_indexing", "remove_metrics"]

# RUSTFLAGS="-C target-cpu=native" cargo bench

# in .cargo/config.toml
# rustflags = ["-C target-cpu=native"]

# rustc --print cfg
# rustc -C target-cpu=native --print cfg
