[package]
name = "flounder"
version = "0.1.0"
authors = ["andy <andy@webcalculator.com>"]
edition = "2018"
description = """
Chess
"""
repository = "https://github.com/akanalytics/flounder"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.2"
lazy_static = "1.4.0"

[dev-dependencies]
criterion = "0.3"


[[bench]]
name = "benchmark"
harness = false



[lib]
name = "flouder"
path = "src/lib.rs"

