[package]
name = "odonata"
version = "0.3.19"
license = "GPL-3.0+"
homepage = "https://github.com/akanalytics/odonata"
authors = ["andy watkins <andy@webcalculator.com>"]
edition = "2018"
description = """
A simple UCI compliant chess engine
"""
keywords = ["chess"]
repository = "https://github.com/akanalytics/odonata"

# for built dependency
build = "build.rs"  

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
bitflags = "1.2"
arrayvec = "0.7"
once_cell = "1.7"
regex = "1.4"
rand = "0.8.3"
rand_chacha = "0.3.0"
env_logger = "0.8" 
log = { version = "0.4", features = ["release_max_level_info"] }
# lazy_static = "1.4"
# crossbeam = "0.8.1"
# ctor = "0.1.20"
static_init = "1.0.1"

[dev-dependencies]
criterion = "0.3"


[build-dependencies]
built = "0.5"

[[bench]]
name = "benchmark"
harness = false


[profile.bench]
debug = true

[profile.release]
#lto = true
#codegen-units = 1
opt-level = 3
debug = false  # disallow profiling of the  main executable 

[lib]
# bug in criterion<->cargo interaction https://bheisler.github.io/criterion.rs/book/faq.html
bench = false

[features]
remove_metrics = []
unchecked_indexing = []
fast = ["unchecked_indexing", "remove_metrics"]

# RUSTFLAGS="-C target-cpu=native" cargo bench

# in .cargo/config.toml
# rustflags = ["-C target-cpu=native"]

# rustc --print cfg
# rustc -C target-cpu=native --print cfg

