max_width = 120
use_small_heuristics = "Default"
reorder_imports = true


edition = "2021"
newline_style = "Unix"
group_imports = "StdExternalCrate"
imports_granularity = "Module"
use_field_init_shorthand = true
# wrap_comments = true
comment_width = 80
struct_field_align_threshold = 40
enum_discrim_align_threshold = 40
condense_wildcard_suffixes = true
# format_strings = true
format_macro_matchers = true
format_macro_bodies = true
normalize_comments = true
# reorder_impl_items = true
format_code_in_doc_comments = true
overflow_delimited_expr = true
normalize_doc_attributes = true
hex_literal_case = "Lower"

tab_spaces = 4
