#
# Run: 73
# MSE improved from 0.060908 to 0.060908 (0.00%)
# MSE improved from 0.060908 to 0.060914 (0.01%) using integer weights
# Training file ../epd/quiet-labeled.epd
# Odonata odonata 0.4.2 built on Mon, 18 Oct 2021 22:14:55 +0000
# Path ../engines/odonata/odonata-stable
# Completed... 93.1 M position evaluations per second (45807 recalcs x 1417268 file lines)
# 

# baseline


shared_tt = true
thread_count = 1
config_filename = "config.toml"
minmax = false

[ids]
enabled = true
part_ply = false
step_size = 1


[eval]
material           = true
position           = true
safety             = true
mobility           = true
pawn               = true


# tuned
center_attacks             = [   7.20,   -1.22]
undefended_sq              = [   4.67,    3.49]
undefended_piece           = [   7.01,   41.75]
trapped_piece              = [ -17.49,  -39.45]
partially_trapped_piece    = [  -3.15,  -15.33]
pawn_doubled               = [  10.09,  -28.81]
pawn_isolated              = [ -38.77,   -6.14]
pawn_passed                = [  -8.82,   33.15]
pawn_passed_r6             = [  21.41,  160.86]
pawn_passed_r5             = [  25.41,   54.36]
passers_on_rim             = [  15.33,    5.39]
blockaded                  = [   7.99,  -30.82]
blockaded_passers          = [ -38.25,  -49.28]
rooks_behind_passer        = [  10.48,   21.34]
space                      = [  -3.29,   -3.27]
rammed_pawns               = [   1.97,    6.53]
bishop_pair                = [  46.74,   77.69]
fianchetto                 = [  58.62,   34.29]
bishop_outposts            = [  73.69,    2.82]
bishop_color_pawns         = [  -7.01,   -3.01]
knight_forks               = [   4.50,   65.64]
knight_outposts            = [  52.67,   22.18]
rook_pair                  = [  18.85,   -4.18]
doubled_rooks              = [  30.49,   11.07]
doubled_rooks_open_file    = [   3.96,   18.06]
rook_open_file             = [  52.39,   -3.40]
enemy_pawns_on_rook_rank   = [ -24.40,   10.41]
queen_open_file            = [ -28.04,   48.68]
queen_early_develop        = [ -15.68,    0.73]
pawn_adjacent_shield       = [  41.96,  -15.14]
pawn_nearby_shield         = [  29.95,  -11.28]
open_files_near_king       = [  -6.56,   -1.93]
attacks_near_king          = [  13.54,   -0.22]
tropism_d1                 = [ -39.96,   22.79]
tropism_d2                 = [ -27.52,   10.71]
tropism_d3                 = [  -7.37,    4.43]
castling_rights            = [   1.73,    7.78]
tempo_bonus                = [  47.35,   46.09]

pst.p = [
  [[   5.22,    8.86], [  10.04,   10.83], [   8.21,   11.24], [   7.68,   10.48], [   7.71,    6.64], [   4.06,    8.53], [   8.66,    7.51], [   8.60,    9.09]], 
  [[ 134.26,  307.11], [  85.23,  318.00], [  59.77,  296.61], [ 115.85,  242.66], [ 140.24,  227.22], [  99.48,  252.99], [  17.22,  313.84], [ -52.47,  307.27]], 
  [[  12.90,   52.44], [   0.56,   45.56], [  51.29,   21.41], [  20.71,  -21.03], [  43.70,  -25.48], [ 146.86,  -19.29], [  10.70,   18.80], [ -11.37,   21.35]], 
  [[  12.31,   24.80], [  -3.77,   23.87], [   0.27,   12.61], [  29.67,  -14.57], [  30.65,   -6.59], [  12.45,    5.06], [ -24.61,   22.06], [ -24.45,    9.06]], 
  [[ -20.26,   10.66], [ -31.36,   15.63], [  -2.48,   -3.14], [  32.29,  -16.04], [  23.40,   -8.78], [   1.50,   -1.68], [ -27.45,    7.79], [ -20.70,   -7.04]], 
  [[ -12.19,  -12.66], [ -28.13,   -4.32], [   6.48,  -12.39], [  -3.48,  -11.93], [   9.86,   -5.86], [ -35.74,    7.28], [   3.93,   -8.67], [  -3.21,  -25.22]], 
  [[ -15.38,   -4.53], [ -18.23,   -2.71], [  -6.47,   -0.32], [   1.90,  -13.03], [  -4.37,    6.18], [  17.87,    4.27], [  22.52,  -12.48], [ -14.04,  -30.76]], 
  [[   6.58,    9.11], [   7.58,    9.21], [   5.86,   11.75], [  13.39,    6.08], [   9.65,   10.58], [   9.80,   10.09], [   1.56,   12.08], [   9.28,    5.40]]
]
pst.n = [
  [[-364.07,   24.42], [-151.69,  -49.07], [ -86.67,  -23.80], [-142.55,   -3.93], [ -24.95,  -32.33], [-319.57,    0.88], [-214.51,  -22.40], [-195.02, -104.59]], 
  [[-137.59,   -8.99], [ -47.18,   -9.57], [  83.23,  -39.02], [ -23.90,    1.72], [  75.06,  -38.00], [  25.07,  -22.89], [ -60.43,  -25.05], [ -88.57,  -41.74]], 
  [[ -24.64,  -40.13], [ -27.29,  -11.64], [  -3.34,   14.54], [  11.88,   10.18], [  33.40,  -14.62], [ 105.57,  -22.54], [   0.43,  -25.89], [ -89.91,  -14.27]], 
  [[   7.98,  -14.76], [ -13.07,    0.23], [ -18.76,   16.05], [  15.87,   30.49], [ -33.34,   19.67], [   9.50,   15.04], [ -51.09,   -8.39], [  18.20,  -28.38]], 
  [[ -22.69,  -18.30], [  -6.24,   -3.28], [   6.23,   15.66], [  12.07,   16.62], [  26.73,   25.19], [  22.94,   -3.34], [   8.49,  -17.03], [ -33.65,   -6.74]], 
  [[ -35.95,  -18.08], [ -13.01,    1.75], [   7.89,    0.46], [  25.23,   18.20], [  37.20,   10.62], [  13.43,   -0.72], [  30.42,  -19.34], [ -25.19,  -23.61]], 
  [[ -23.21,  -31.12], [ -44.68,  -15.25], [  -3.48,  -12.51], [  25.87,   -8.96], [  16.45,   -8.94], [  29.41,   -6.34], [   8.43,  -15.64], [  -1.32,  -27.64]], 
  [[ -73.38,  -57.22], [ -26.09,   12.76], [ -53.93,    3.31], [ -28.44,   14.91], [ -10.39,  -11.03], [ -12.19,    5.27], [ -27.28,    0.51], [ -94.55,   -6.41]]
]
pst.b = [
  [[ -66.75,   -0.76], [ -84.59,  -14.83], [ -60.33,   -5.52], [-155.40,   18.69], [-246.93,   25.54], [-166.77,   15.50], [ -85.54,    6.11], [ -75.66,    9.64]], 
  [[ -88.94,    6.99], [ -29.45,   -0.30], [ -61.00,   11.49], [ -52.55,   -1.83], [ -79.65,   19.11], [ -18.15,   -2.08], [ -92.58,   12.29], [ -86.29,  -16.81]], 
  [[ -45.23,    7.20], [ -21.16,   -2.04], [  24.18,   -2.99], [ -50.18,   28.80], [   7.77,    4.64], [  -9.02,   20.24], [ -18.36,    4.53], [ -32.71,   -3.62]], 
  [[ -39.26,    7.74], [ -44.92,   13.93], [ -12.73,    6.16], [ -21.96,   15.79], [   4.15,    4.31], [ -58.43,   12.02], [ -13.45,   -8.12], [ -37.83,  -13.31]], 
  [[ -16.33,  -13.61], [ -13.35,   -4.19], [ -13.58,    8.37], [  30.73,   -9.43], [  18.70,    2.93], [  -7.22,   13.68], [   2.84,  -11.10], [ -16.57,  -23.62]], 
  [[  17.63,  -26.98], [  15.45,   -5.19], [  33.16,   -5.10], [  -8.21,   18.84], [  17.46,   11.08], [  20.80,    1.27], [  12.88,  -12.77], [   6.09,  -19.71]], 
  [[ -31.69,   -9.55], [  29.92,  -31.32], [   3.20,  -14.25], [  14.13,   -4.24], [   1.64,   11.10], [  51.26,  -12.18], [  41.98,  -15.02], [  11.73,  -34.38]], 
  [[   4.20,  -40.62], [ -19.28,   -9.98], [   8.21,   -6.15], [  -8.28,    2.77], [   4.08,    5.47], [ -42.48,   28.70], [ -13.67,  -17.21], [ -14.60,  -23.43]]
]
pst.r = [
  [[  45.11,    7.17], [  75.62,   -4.40], [  63.60,    1.04], [  38.82,    3.88], [  41.91,    5.78], [  66.41,   -1.09], [  78.98,    5.59], [   4.26,   13.81]], 
  [[  25.15,   -7.74], [   5.58,   13.27], [  14.71,    9.72], [  44.20,    0.49], [ -72.06,   28.15], [  16.54,   22.89], [  62.20,    5.99], [  51.84,   -3.91]], 
  [[  28.74,   -2.42], [  12.41,    3.47], [ -19.71,    9.70], [   3.88,   15.95], [ -41.30,   25.93], [  -2.59,   13.95], [  37.81,    8.98], [  15.78,   -2.94]], 
  [[ -26.07,    7.69], [  -4.96,    2.60], [  -7.35,   16.03], [ -13.09,   19.73], [ -47.07,   24.98], [  -7.79,   16.00], [   1.52,    7.68], [  32.52,   -7.45]], 
  [[ -31.92,    1.13], [ -46.07,   14.65], [ -62.78,   26.40], [ -51.01,   30.51], [ -33.51,   27.45], [ -36.72,   13.69], [  -1.14,   -2.74], [ -18.12,   -9.65]], 
  [[ -55.15,    3.26], [ -33.27,    3.80], [ -37.64,   10.82], [ -19.47,    8.39], [ -19.62,    8.93], [ -15.72,   -1.25], [  12.55,  -13.87], [ -17.75,  -12.96]], 
  [[ -34.82,   -0.23], [ -10.07,    1.81], [ -27.66,   21.54], [ -13.98,    9.17], [  -2.05,    3.16], [  11.30,   -0.82], [  29.36,   -5.00], [ -85.51,   14.42]], 
  [[ -15.92,   17.26], [  -0.46,   13.57], [   7.76,    6.96], [  12.08,   10.74], [  33.76,   -6.06], [  35.11,   -7.18], [ -36.23,   12.63], [  -6.56,  -22.23]]
]
pst.q = [
  [[ -73.95,   -2.19], [   8.27,  -19.39], [ -21.81,   -2.50], [  12.38,    5.89], [   0.34,   -5.90], [  -9.13,   19.70], [  -8.72,  -10.01], [  -3.52,   23.25]], 
  [[ -64.55,  -11.12], [ -96.32,  -13.32], [-110.10,   11.51], [-156.57,   79.87], [-260.02,  104.43], [ -85.33,  114.09], [-151.67,   76.67], [  40.31,  -37.65]], 
  [[ -44.83,  -46.53], [ -54.30,  -26.14], [ -63.99,   20.02], [ -71.63,   21.97], [ -80.42,   89.03], [ -53.15,   30.41], [  31.60,   -1.21], [ -58.77,   31.11]], 
  [[ -53.11,  -16.00], [ -56.48,   20.09], [ -68.89,   -5.21], [-102.96,   34.87], [ -81.83,   54.88], [ -75.69,   69.12], [ -66.26,   60.38], [ -29.85,   24.38]], 
  [[ -32.23,   -9.93], [ -29.40,   -4.76], [ -40.48,   -8.25], [ -63.25,   31.05], [ -34.05,   17.51], [ -32.13,   12.18], [  -2.65,   13.46], [ -19.15,   17.24]], 
  [[ -35.46,  -43.29], [  -8.19,  -47.50], [ -22.83,    3.82], [ -22.95,   -2.18], [ -21.43,    8.55], [ -12.01,    0.37], [  -1.49,   19.11], [ -13.29,   -4.47]], 
  [[  -5.21,  -17.25], [  12.33,  -20.15], [   6.49,  -15.00], [  13.04,   -8.43], [  24.85,  -29.47], [  49.08,  -71.06], [  47.70,  -81.32], [   7.34,  -12.97]], 
  [[  11.41,  -33.24], [  15.07,  -49.15], [  19.56,  -44.36], [  14.22,  -27.38], [  25.63,  -27.12], [   5.20,  -46.49], [ -37.93,  -32.43], [   4.74,  -61.14]]
]
pst.k = [
  [[   4.43, -127.54], [  45.46,  -69.17], [  85.14,  -71.85], [  47.14,  -49.78], [ 107.54,  -65.10], [  87.44,  -48.09], [ -40.53,  -37.70], [ -99.77,  -67.89]], 
  [[ -27.57,  -60.53], [ 158.98,  -34.60], [ 111.69,  -35.22], [  41.54,  -25.29], [  40.44,  -24.59], [ 160.60,  -15.60], [   8.95,    4.68], [ -97.18,   -9.53]], 
  [[  29.53,  -51.97], [ 212.34,  -31.12], [  84.13,  -12.76], [  97.38,  -16.43], [  57.36,   -5.41], [ 181.48,   -4.59], [ 177.46,    4.03], [ -66.45,   -4.07]], 
  [[ -35.44,  -48.25], [  56.27,  -17.10], [ 105.38,   -8.44], [  64.04,    5.69], [  37.72,    4.94], [  60.71,    9.06], [  38.40,    1.88], [ -79.58,   -6.93]], 
  [[  29.34,  -71.02], [ 118.70,  -29.58], [  97.50,   -1.54], [   6.87,   20.24], [  28.73,   18.61], [ -20.40,   18.40], [ -38.06,    8.68], [-143.60,   -7.73]], 
  [[  35.10,  -57.46], [  86.00,  -12.95], [   4.94,   21.35], [ -21.68,   35.50], [ -24.08,   34.38], [  -1.70,   26.29], [   3.95,   10.31], [ -61.41,  -10.67]], 
  [[  52.57,  -47.05], [  -8.41,    8.87], [  15.46,   25.11], [ -51.48,   47.90], [ -34.92,   43.26], [ -40.06,   42.11], [  15.88,   13.89], [   2.27,  -22.20]], 
  [[ -77.05,  -39.05], [  11.75,  -21.90], [  14.79,    1.95], [ -59.12,   11.32], [   4.22,  -12.20], [ -67.50,   13.61], [   3.62,  -23.01], [  10.91,  -82.56]]
]

# [eval.attacks.p]
# p = [0.1, 0.2]
# n = [0.0, 0.0]
# b = [0.0, 0.0]
# r = [0.0, 0.0]
# q = [0.0, 0.0]
# k = [0.0, 0.0]

# [eval.attacks.n]
# p = [0.0, 0.3]
# n = [0.0, 0.0]
# b = [0.0, 0.0]
# r = [0.0, 0.0]
# q = [0.0, 0.0]
# k = [0.0, 0.0]

# [eval.attacks.b]
# p = [0.0, 0.0]
# n = [0.0, 0.0]
# b = [0.0, 0.0]
# r = [0.0, 0.0]
# q = [0.0, 0.0]
# k = [0.0, 0.0]

# [eval.attacks.r]
# p = [0.0, 0.0]
# n = [0.0, 0.0]
# b = [0.0, 0.0]
# r = [0.0, 0.0]
# q = [0.0, 0.0]
# k = [0.0, 0.0]

# [eval.attacks.q]
# p = [0.0, 0.0]
# n = [0.0, 0.0]
# b = [0.0, 0.0]
# r = [0.0, 0.0]
# q = [0.0, 0.0]
# k = [0.0, 0.0]

# [eval.attacks.k]
# p = [0.0, 0.0]
# n = [0.0, 0.0]
# b = [0.0, 0.0]
# r = [0.0, 0.0]
# q = [0.0, 0.0]
# k = [0.0, 0.0]

# [eval.defends.p]
# p = [0.0, 0.0]
# n = [0.0, 0.0]
# b = [0.0, 0.0]
# r = [0.0, 0.0]
# q = [0.0, 0.0]
# k = [0.0, 0.0]

# [eval.defends.n]
# p = [0.0, 0.0]
# n = [0.0, 0.0]
# b = [0.0, 0.0]
# r = [0.0, 0.0]
# q = [0.0, 0.0]
# k = [0.0, 0.0]

# [eval.defends.b]
# p = [0.0, 0.0]
# n = [0.0, 0.0]
# b = [0.0, 0.0]
# r = [0.0, 0.0]
# q = [0.0, 0.0]
# k = [0.0, 0.0]

# [eval.defends.r]
# p = [0.0, 0.0]
# n = [0.0, 0.0]
# b = [0.0, 0.0]
# r = [0.0, 0.0]
# q = [0.0, 0.0]
# k = [0.0, 0.0]

# [eval.defends.q]
# p = [0.0, 0.0]
# n = [0.0, 0.0]
# b = [0.0, 0.0]
# r = [0.0, 0.0]
# q = [0.0, 0.0]
# k = [0.0, 0.0]

# [eval.defends.k]
# p = [0.0, 0.0]
# n = [0.0, 0.0]
# b = [0.0, 0.0]
# r = [0.0, 0.0]
# q = [0.0, 0.0]
# k = [0.0, 0.0]

# attacks.p.p               = [   0,   0]
# defends.p.p               = [   8.68,   11.21]
# attacks.p.n               = [  10.64,    8.40]
# defends.p.n               = [   8.19,   15.23]
# attacks.p.b               = [  10.28,   12.50]
# defends.p.b               = [   9.47,   10.94]
# attacks.p.r               = [  14.52,   11.58]
# defends.p.r               = [   7.76,    9.05]
# attacks.p.q               = [   8.42,   13.97]
# defends.p.q               = [   8.65,    8.79]
# attacks.p.k               = [   8.52,   12.53]
# defends.p.k               = [   8.98,   10.90]
# attacks.n.p               = [  -5.61,  -10.47]
# defends.n.p               = [  -0.24,   12.19]
# attacks.n.n               = [   8.36,    8.02]
# defends.n.n               = [   4.76,    4.81]
# attacks.n.b               = [  42.29,   42.49]
# defends.n.b               = [   5.67,    1.58]
# attacks.n.r               = [ 105.87,    6.41]
# defends.n.r               = [   8.00,   -3.61]
# attacks.n.q               = [  49.43,   -0.50]
# defends.n.q               = [   9.91,  -18.53]
# attacks.n.k               = [ 187.11,   -9.77]
# defends.n.k               = [   4.88,   -0.39]
# attacks.b.p               = [  -5.84,   -7.82]
# defends.b.p               = [   3.84,    2.11]
# attacks.b.n               = [  26.01,   29.04]
# defends.b.n               = [  11.25,   22.76]
# attacks.b.b               = [  10.61,   10.38]
# defends.b.b               = [  12.94,    7.63]
# attacks.b.r               = [  67.62,   -8.06]
# defends.b.r               = [   1.84,   18.60]
# attacks.b.q               = [  91.87,   11.12]
# defends.b.q               = [  15.07,    1.44]
# attacks.b.k               = [  91.04,   73.46]
# defends.b.k               = [   7.57,    2.30]
# attacks.r.p               = [ -11.63,    0.91]
# defends.r.p               = [  -9.15,    9.73]
# attacks.r.n               = [   3.06,   17.31]
# defends.r.n               = [   8.15,   19.15]
# attacks.r.b               = [  20.48,    5.23]
# defends.r.b               = [  12.57,   17.38]
# attacks.r.r               = [  11.14,   11.35]
# defends.r.r               = [   1.14,   13.71]
# attacks.r.q               = [  99.04,  -17.16]
# defends.r.q               = [  15.97,   24.39]
# attacks.r.k               = [ 268.09,  -25.06]
# defends.r.k               = [  11.53,   -6.96]
# attacks.q.p               = [  -0.74,   -8.18]
# defends.q.p               = [   2.72,   -0.02]
# attacks.q.n               = [   0.22,    2.63]
# defends.q.n               = [   9.58,   10.15]
# attacks.q.b               = [   1.41,   26.16]
# defends.q.b               = [   5.03,   16.53]
# attacks.q.r               = [  11.43,  -34.40]
# defends.q.r               = [   2.11,    8.43]
# attacks.q.q               = [  11.38,   10.63]
# defends.q.q               = [-239.84, -145.59]
# attacks.q.k               = [  97.67,  115.74]
# defends.q.k               = [  -4.67,  -24.98]
# attacks.k.p               = [  12.76,   15.32]
# defends.k.p               = [  12.74,   11.81]
# attacks.k.n               = [  11.42,   11.58]
# defends.k.n               = [  11.65,   11.75]
# attacks.k.b               = [  12.21,    8.58]
# defends.k.b               = [  12.68,    8.58]
# attacks.k.r               = [  11.11,   12.00]
# defends.k.r               = [  11.16,   12.59]
# attacks.k.q               = [  12.02,   11.71]
# defends.k.q               = [   9.32,   14.62]
# attacks.k.k               = [  11.86,   12.76]
# defends.k.k               = [  10.60,   0

[eval.mb]
enabled = false
filename = ""
consistency_report = true
consistency_adjust = true
internal_stats = false
draws_only = false
min_games = 50
max_pawns = 5
trade_factor = 2
p = [ 137.45,  140.34]
n = [ 623.12,  390.26]
b = [ 645.12,  417.44]
r = [ 846.55,  744.55]
q = [1846.25, 1379.75]
k = [   0.00,    0.00]


balances.NKk = 0
balances.BKk = 0


[eval.phaser]
enabled = true
method = "SO"
half_way_score = 3200



[qsearch]
enabled = true
only_on_capture = false
promos = false
ignore_see_fails = true
see_cutoff = 1
max_ply = 10
coarse_delta_prune = 1000
switches = 1279

[nmp]
enabled = true
recursive = true
successive = true
min_depth = 2
depth_reduction_strat = 100
a = 2.7
b = 0.198
c = 0.00017


[razor]
enabled = true
max_depth = 3
min_opponents = 4
pv_nodes = false
margin1 = 94
margin2 = 381
margin3 = 873
move_types_forbidden = 994

[futility]
alpha_enabled = true
beta_enabled = false
prune_remaining = false
avoid_checks = false
avoid_promos = false
promo_margin = false
max_depth = 2
max_depth_captures = 2
margin1 = 100
margin2 = 250
margin3 = 1500
eval_switches = 255
move_types_forbidden = 0

[pvs]
enabled = true
min_depth = 2

[extensions]
check_enabled = false
check_max_depth = 3
check_max_phase = 60
promo_enabled = false
promo_max_depth = 1
promo_rank = 7
promo_extend = 1

[lmr]
enabled = true
pv_node = true
only_nt_all = false
bad_captures = true
pawns = true
promos = false
killers = false
min_depth = 2
re_search = false
alpha_numeric = false
reduce_extensions = false
red_strat = 6

[mte]
branching_factor = 15
perc_of_time_adv = 100
moves_rem = 10
deterministic = false
nodestime = 0

[move_orderer]
enabled = true
prior_pv = true
prior_bm = false
tt_bm = true
mvv_lva = true
order = ["Start", "Hash", "Initialize", "GoodCaptureUpfrontSorted", "Killer", "Promo", "Quiet", "BadCapture", "End"]
qorder = ["Start", "Initialize", "Capture", "End"]

[repetition]
enabled = true
avoid_tt_on_repeats = false

[tt]
aging = true
probe_leaf_nodes = true
enabled = true
use_tt_for_pv = false
allow_truncated_pv = false
allow_tt_at_root = false
mb = 8
hmvc_horizon = 85
min_ply = 1

[killers]
enabled = true
clear_every_move = false
use_ply_below = true

[history]
enabled = true
scale = 1
age_factor = 4

[explainer]
enabled = false

[restrictions]
enabled = true




#end of file
