#
# Run: 38
# MSE improved from 0.070262 to 0.062949 (-10.41%)
# MSE improved from 0.070262 to 0.062954 (-10.40%) using integer weights
# Training file ../epd/quiet-labeled.epd
# Odonata odonata 0.3.41 built on Sat, 11 Sep 2021 10:36:00 +0000
# Path ../engines/odonata/odonata-stable
# Completed... 112.7 M position evaluations per second (9457 recalcs x 1417268 file lines)
# 

# baseline
eval.material=true
eval.position=true
eval.safety=true
eval.mobility=true
eval.pawn=true
mb.enabled=false
phaser.method="SO"

# tuned
eval.p.e=152
eval.n.s=631
eval.n.e=404
eval.b.s=643
eval.b.e=431
eval.r.s=850
eval.r.e=775
eval.q.s=1809
eval.q.e=1434
eval.mobility.undef.sq.s=4
eval.mobility.undef.sq.e=3
eval.mobility.undef.piece.s=-2
eval.mobility.undef.piece.e=46
eval.mobility.trapped.piece.s=-14
eval.mobility.trapped.piece.e=-18
eval.mobility.partially.trapped.piece.s=-6
eval.mobility.partially.trapped.piece.e=-18
eval.pawn.r5.s=16
eval.pawn.r5.e=10
eval.pawn.r6.s=19
eval.pawn.r6.e=52
eval.pawn.r7.s=57
eval.pawn.r7.e=313
eval.pawn.doubled.s=16
eval.pawn.doubled.e=-35
eval.pawn.isolated.s=-35
eval.pawn.isolated.e=-5
eval.pawn.passed.s=16
eval.pawn.passed.e=12
eval.pawn.passed.r5.s=21
eval.pawn.passed.r5.e=64
eval.pawn.passed.r6.s=4
eval.pawn.passed.r6.e=141
eval.passers.on.rim.s=-19
eval.passers.on.rim.e=20
eval.blockaded.s=26
eval.blockaded.e=-41
eval.blockaded.passers.s=-35
eval.blockaded.passers.e=-44
eval.tempo.bonus.s=41
eval.tempo.bonus.e=49
eval.pawn.adjacent.shield.s=44
eval.pawn.adjacent.shield.e=-13
eval.pawn.nearby.shield.s=40
eval.pawn.nearby.shield.e=-10
eval.open.files.near.king.s=-7
eval.open.files.near.king.e=-1
eval.attacks.near.king.s=-9
eval.attacks.near.king.e=-1
eval.tropism.d1.s=-32
eval.tropism.d1.e=23
eval.tropism.d2.s=-29
eval.tropism.d2.e=11
eval.tropism.d3.s=-3
eval.tropism.d3.e=1
eval.rook.open.file.s=58
eval.rook.open.file.e=-1
eval.rook.pair.s=-5
eval.rook.pair.e=-5
eval.queen.open.file.s=-20
eval.queen.open.file.e=39
eval.fianchetto.s=50
eval.fianchetto.e=26
eval.bishop.pair.s=57
eval.bishop.pair.e=69
eval.bishop.color.pawns.s=-6
eval.bishop.color.pawns.e=-4
eval.knight.forks.s=1
eval.knight.forks.e=68
eval.knight.outposts.s=57
eval.knight.outposts.e=19

#end of file
