#
# Run: 73
# MSE improved from 0.060908 to 0.060908 (0.00%)
# MSE improved from 0.060908 to 0.060914 (0.01%) using integer weights
# Training file ../epd/quiet-labeled.epd
# Odonata odonata 0.4.2 built on Mon, 18 Oct 2021 22:14:55 +0000
# Path ../engines/odonata/odonata-stable
# Completed... 93.1 M position evaluations per second (45807 recalcs x 1417268 file lines)
# 

# baseline


shared_tt = true
thread_count = 1
config_filename = "config.toml"
minmax = false

[ids]
enabled = true
part_ply = true
step_size = 1


[eval]
material           = true
position           = true
safety             = true
mobility           = true
pawn               = true


# tuned

center_attacks            = [   7.62,   -1.27]
undefended_sq             = [   4.63,    3.37]
undefended_piece          = [   6.35,   42.25]
trapped_piece             = [ -17.74,  -39.83]
partially_trapped_piece   = [  -3.45,  -14.61]
pawn_doubled              = [  10.53,  -29.78]
pawn_isolated             = [ -38.91,   -5.40]
pawn_passed               = [  -5.68,   32.89]
pawn_passed_r6            = [  27.03,  161.89]
pawn_passed_r5            = [  31.33,   55.37]
passers_on_rim            = [  18.15,    3.86]
blockaded                 = [   8.17,  -31.03]
blockaded_passers         = [ -40.97,  -47.75]
bishop_pair               = [  48.44,   75.41]
fianchetto                = [  63.51,   32.62]
bishop_outposts           = [  73.78,    0.92]
bishop_color_pawns        = [  -7.04,   -3.15]
knight_forks              = [   4.98,   66.55]
knight_outposts           = [  53.69,   25.83]
rook_pair                 = [  17.45,   -3.01]
doubled_rooks             = [  29.69,   14.12]
doubled_rooks_open_file   = [   3.81,   14.65]
rook_open_file            = [  50.68,   -2.88]
queen_open_file           = [ -27.83,   47.84]
queen_early_develop       = [ -15.20,   -0.02]
pawn_adjacent_shield      = [  42.21,  -15.04]
pawn_nearby_shield        = [  30.59,  -11.52]
open_files_near_king      = [  -6.53,   -1.83]
attacks_near_king         = [  13.87,   -0.06]
tropism_d1                = [ -39.85,   22.91]
tropism_d2                = [ -26.92,   10.67]
tropism_d3                = [  -6.48,    4.25]
castling_rights           = [   1.88,    9.09]
contempt_penalty          = [ -25.65,    0.00]
tempo_bonus               = [  47.37,   46.05]



pst.p = [
  [[   5.39,    3.43], [   9.74,    8.97], [   8.39,    8.64], [   8.20,   10.32], [   8.28,    3.47], [  10.31,    4.66], [   7.69,   13.53], [   1.32,    7.22]], 
  [[ 143.96,  309.91], [  85.57,  317.82], [  60.01,  299.09], [ 115.44,  245.31], [ 141.84,  228.82], [ 106.31,  250.45], [  17.63,  311.18], [ -38.23,  306.52]], 
  [[   0.45,   49.58], [  -8.15,   42.35], [  44.21,   19.03], [   9.38,  -21.13], [  36.02,  -28.11], [ 132.08,  -22.11], [   5.93,   15.50], [ -27.25,   18.00]], 
  [[   8.38,   22.33], [  -6.03,   20.26], [  -3.30,   10.39], [  20.75,  -18.09], [  22.32,  -10.65], [  10.55,    2.58], [ -28.24,   19.07], [ -29.93,    6.08]], 
  [[ -19.00,   10.93], [ -30.44,   15.22], [  -2.46,   -2.94], [  32.20,  -15.79], [  23.98,   -9.21], [   1.43,   -2.11], [ -26.97,    7.74], [ -20.41,   -7.23]], 
  [[ -10.88,  -10.96], [ -27.68,   -3.40], [   6.67,  -12.42], [  -2.15,   -8.84], [  11.58,   -4.31], [ -36.43,    7.74], [   3.88,   -7.65], [  -2.95,  -24.65]], 
  [[ -14.69,   -3.21], [ -17.86,   -2.01], [  -6.71,   -0.49], [   2.04,  -11.76], [  -3.97,    6.29], [  17.64,    4.41], [  22.32,  -11.65], [ -14.04,  -30.84]], 
  [[   8.81,    8.72], [  12.48,    9.15], [   6.57,    3.59], [   7.61,    5.37], [   9.81,    1.60], [   1.94,    7.91], [   8.32,    8.76], [   0.63,    7.00]]
]
pst.n = [
  [[-371.55,   23.43], [-110.92,  -57.40], [ -80.87,  -24.70], [-134.26,  -10.92], [ -39.99,  -28.86], [-311.33,   -1.61], [-212.73,  -18.45], [-195.24, -104.03]], 
  [[-139.48,   -6.90], [ -48.25,   -9.94], [  82.90,  -38.08], [ -20.89,   -0.76], [  73.75,  -37.99], [  23.47,  -23.26], [ -49.71,  -29.46], [ -95.09,  -39.55]], 
  [[ -17.95,  -43.08], [ -28.02,   -9.86], [  -6.18,   16.29], [  15.53,    8.17], [  31.62,  -16.04], [  97.97,  -20.94], [   4.94,  -28.81], [ -86.48,  -16.90]], 
  [[   7.22,  -14.89], [ -13.06,   -0.55], [ -18.45,   14.54], [  14.46,   27.98], [ -33.94,   19.09], [   9.88,   11.26], [ -51.52,   -9.22], [  19.85,  -26.95]], 
  [[ -24.60,  -14.41], [  -1.52,   -2.47], [   5.19,   15.44], [  11.07,   16.35], [  25.72,   25.22], [  21.07,   -3.79], [   5.80,  -18.43], [ -35.95,   -4.98]], 
  [[ -36.24,  -19.74], [ -13.30,   -1.13], [   7.68,   -0.36], [  22.95,   18.71], [  35.90,   11.12], [  12.31,   -0.63], [  30.25,  -20.30], [ -25.55,  -25.57]], 
  [[ -24.49,  -24.60], [ -41.84,  -11.25], [  -4.43,   -9.43], [  25.13,   -8.87], [  15.45,   -9.08], [  29.34,   -4.34], [   4.36,  -12.50], [  -1.50,  -25.34]], 
  [[ -70.17,  -53.38], [ -26.79,   11.21], [ -53.36,    0.54], [ -30.24,   14.89], [ -11.10,  -12.68], [ -15.74,    7.22], [ -28.16,   -0.98], [-106.52,   -2.74]]
]
pst.b = [
  [[ -70.04,    1.62], [ -88.64,  -14.45], [ -68.34,   -3.66], [-147.39,   16.39], [-245.01,   26.82], [-174.72,   22.36], [ -77.19,    4.71], [ -78.04,   10.92]], 
  [[ -87.76,    6.58], [ -29.85,    1.00], [ -57.99,   11.39], [ -51.46,   -0.96], [ -73.67,   17.70], [ -20.19,    0.07], [ -89.06,   14.25], [ -83.15,  -15.55]], 
  [[ -45.66,    7.97], [ -20.85,   -1.43], [  26.47,   -2.66], [ -46.72,   29.48], [  14.45,    5.12], [  -7.52,   19.53], [ -14.93,    4.21], [ -31.27,   -1.24]], 
  [[ -39.81,    9.54], [ -44.26,   14.61], [ -13.85,    7.17], [ -22.97,   17.07], [   4.99,    4.84], [ -56.30,   13.04], [ -12.31,   -6.65], [ -35.47,  -14.03]], 
  [[ -16.80,  -13.72], [ -13.95,   -2.51], [ -13.50,    8.92], [  29.17,   -9.17], [  18.89,    4.19], [  -6.84,   14.94], [   0.92,   -9.58], [ -17.22,  -22.03]], 
  [[  17.99,  -25.92], [  15.91,   -6.05], [  33.60,   -4.68], [  -7.83,   18.74], [  17.40,   12.10], [  20.07,    1.47], [  11.77,  -13.34], [   6.47,  -20.09]], 
  [[ -31.83,  -11.03], [  29.36,  -30.56], [   2.61,  -14.13], [  13.97,   -4.85], [   1.34,   11.46], [  50.23,  -11.96], [  41.62,  -15.89], [  10.89,  -34.79]], 
  [[   1.35,  -35.22], [ -23.66,   -6.30], [   7.88,   -5.52], [  -9.49,    3.38], [   3.04,    4.06], [ -42.58,   29.72], [  -3.70,  -23.66], [ -16.51,  -21.92]]
]
pst.r = [
  [[  48.82,    2.74], [  93.55,  -12.62], [  67.20,   -2.06], [  32.05,    1.51], [  32.73,    4.55], [  49.18,    0.06], [  68.47,    6.32], [  -9.80,   15.00]], 
  [[ -12.52,   -0.94], [ -43.57,   25.23], [ -24.82,   17.50], [   9.55,    9.76], [-119.34,   40.59], [  -1.55,   24.95], [  42.62,    8.83], [  13.85,    4.72]], 
  [[   2.13,    3.22], [ -11.18,    8.38], [ -36.38,   12.65], [ -19.83,   20.98], [ -59.51,   30.09], [ -19.63,   17.85], [  30.34,    9.86], [  -1.58,   -0.58]], 
  [[ -42.68,   10.50], [ -21.05,    7.19], [ -26.00,   19.32], [ -28.97,   23.87], [ -61.39,   28.86], [ -28.00,   21.18], [ -17.25,   10.53], [  16.11,   -5.63]], 
  [[ -35.97,    2.05], [ -51.02,   14.73], [ -72.42,   28.44], [ -51.71,   27.84], [ -41.52,   28.24], [ -41.95,   13.74], [ -14.75,    2.72], [ -23.27,  -10.61]], 
  [[ -54.54,    1.51], [ -34.63,    1.43], [ -37.51,    8.34], [ -20.00,    6.92], [ -22.36,    8.76], [ -14.00,   -4.65], [   5.26,  -13.30], [ -23.96,  -14.24]], 
  [[ -32.69,   -2.10], [  -9.76,    1.20], [ -26.43,   18.17], [ -13.28,    6.24], [  -2.46,    1.31], [  11.61,   -3.21], [  34.41,   -8.48], [ -85.32,    9.89]], 
  [[ -13.37,   15.47], [   2.28,   11.80], [  10.31,    4.66], [  13.91,    9.14], [  34.32,   -7.11], [  36.14,  -10.22], [ -36.13,   11.89], [  -5.79,  -24.32]]
]
pst.q = [
  [[ -83.69,    1.07], [ -10.92,   -7.16], [ -34.79,    9.25], [  18.99,    6.66], [  10.19,  -10.75], [   8.54,   15.87], [ -26.49,    3.70], [ -10.40,   24.98]], 
  [[ -61.04,  -12.08], [ -94.21,  -13.82], [-110.03,    8.18], [-153.05,   76.17], [-256.87,  108.58], [ -76.63,  106.02], [-149.90,   77.37], [  50.85,  -40.14]], 
  [[ -45.72,  -45.69], [ -52.18,  -25.92], [ -62.57,   20.80], [ -66.42,   19.69], [ -76.37,   88.63], [ -47.22,   29.55], [  25.28,    7.48], [ -55.33,   29.17]], 
  [[ -47.44,  -21.43], [ -54.80,   18.22], [ -65.70,   -8.09], [-100.97,   36.35], [ -77.84,   53.06], [ -72.66,   68.29], [ -66.84,   60.07], [ -25.87,   19.97]], 
  [[ -31.83,   -9.59], [ -28.88,   -6.16], [ -40.43,   -7.19], [ -64.05,   32.27], [ -34.33,   15.23], [ -34.04,   13.57], [  -4.87,   17.32], [ -16.82,   16.75]], 
  [[ -32.99,  -50.51], [  -7.12,  -52.58], [ -22.75,    3.56], [ -24.63,   -0.74], [ -23.44,   11.30], [ -12.31,    1.40], [  -1.55,   21.74], [ -11.62,    0.89]], 
  [[  -1.52,  -16.66], [  13.26,  -14.15], [   5.96,  -14.29], [  11.96,   -2.84], [  23.69,  -24.92], [  46.33,  -65.33], [  46.54,  -75.35], [  -0.62,   -1.53]], 
  [[  16.01,  -35.56], [  16.07,  -46.44], [  18.57,  -42.78], [  14.50,  -28.92], [  26.90,  -25.99], [   2.23,  -36.54], [ -37.94,  -23.03], [  -2.14,  -49.08]]
]
pst.k = [
  [[   2.54, -131.12], [   3.84,  -56.52], [ 104.61,  -79.80], [   9.78,  -44.64], [ 173.68,  -72.98], [  92.43,  -40.78], [  27.61,  -48.60], [   5.27,  -91.03]], 
  [[   2.92,  -61.54], [ 174.67,  -35.53], [  82.99,  -30.23], [  44.89,  -22.07], [  12.38,  -19.74], [ 148.50,  -10.93], [  10.78,    6.94], [-101.89,   -9.74]], 
  [[  43.52,  -54.22], [ 237.60,  -32.83], [  72.96,   -9.27], [ 116.52,  -18.06], [  51.48,   -2.96], [ 179.67,   -2.22], [ 184.17,    3.44], [ -37.25,   -4.46]], 
  [[ -14.73,  -50.35], [  62.25,  -16.64], [ 118.18,   -9.45], [  69.71,    3.83], [  32.72,    6.26], [  71.89,    8.12], [  41.46,    2.34], [ -83.18,   -4.96]], 
  [[  39.76,  -72.13], [ 104.94,  -25.03], [ 105.96,   -2.69], [  -2.24,   21.93], [  30.57,   18.54], [ -17.46,   18.20], [ -35.30,    7.87], [-144.82,   -6.37]], 
  [[  24.23,  -54.80], [  83.82,  -13.44], [   7.04,   20.24], [ -13.57,   34.00], [ -24.63,   34.07], [  -2.74,   27.29], [   5.20,   10.35], [ -62.72,  -10.07]], 
  [[  58.97,  -47.38], [  -4.91,    8.39], [  18.03,   23.95], [ -49.54,   46.19], [ -33.52,   42.93], [ -38.81,   41.81], [  15.02,   14.73], [   3.99,  -22.59]], 
  [[ -76.70,  -38.69], [  12.60,  -22.38], [  15.54,    2.99], [ -56.49,   10.37], [   4.63,  -12.83], [ -67.04,   14.33], [   4.12,  -22.41], [  11.84,  -81.52]]
]


# [eval.attacks.p]
# p = [0.1, 0.2]
# n = [0.0, 0.0]
# b = [0.0, 0.0]
# r = [0.0, 0.0]
# q = [0.0, 0.0]
# k = [0.0, 0.0]

# [eval.attacks.n]
# p = [0.0, 0.3]
# n = [0.0, 0.0]
# b = [0.0, 0.0]
# r = [0.0, 0.0]
# q = [0.0, 0.0]
# k = [0.0, 0.0]

# [eval.attacks.b]
# p = [0.0, 0.0]
# n = [0.0, 0.0]
# b = [0.0, 0.0]
# r = [0.0, 0.0]
# q = [0.0, 0.0]
# k = [0.0, 0.0]

# [eval.attacks.r]
# p = [0.0, 0.0]
# n = [0.0, 0.0]
# b = [0.0, 0.0]
# r = [0.0, 0.0]
# q = [0.0, 0.0]
# k = [0.0, 0.0]

# [eval.attacks.q]
# p = [0.0, 0.0]
# n = [0.0, 0.0]
# b = [0.0, 0.0]
# r = [0.0, 0.0]
# q = [0.0, 0.0]
# k = [0.0, 0.0]

# [eval.attacks.k]
# p = [0.0, 0.0]
# n = [0.0, 0.0]
# b = [0.0, 0.0]
# r = [0.0, 0.0]
# q = [0.0, 0.0]
# k = [0.0, 0.0]

# [eval.defends.p]
# p = [0.0, 0.0]
# n = [0.0, 0.0]
# b = [0.0, 0.0]
# r = [0.0, 0.0]
# q = [0.0, 0.0]
# k = [0.0, 0.0]

# [eval.defends.n]
# p = [0.0, 0.0]
# n = [0.0, 0.0]
# b = [0.0, 0.0]
# r = [0.0, 0.0]
# q = [0.0, 0.0]
# k = [0.0, 0.0]

# [eval.defends.b]
# p = [0.0, 0.0]
# n = [0.0, 0.0]
# b = [0.0, 0.0]
# r = [0.0, 0.0]
# q = [0.0, 0.0]
# k = [0.0, 0.0]

# [eval.defends.r]
# p = [0.0, 0.0]
# n = [0.0, 0.0]
# b = [0.0, 0.0]
# r = [0.0, 0.0]
# q = [0.0, 0.0]
# k = [0.0, 0.0]

# [eval.defends.q]
# p = [0.0, 0.0]
# n = [0.0, 0.0]
# b = [0.0, 0.0]
# r = [0.0, 0.0]
# q = [0.0, 0.0]
# k = [0.0, 0.0]

# [eval.defends.k]
# p = [0.0, 0.0]
# n = [0.0, 0.0]
# b = [0.0, 0.0]
# r = [0.0, 0.0]
# q = [0.0, 0.0]
# k = [0.0, 0.0]

# attacks.p.p               = [   0,   0]
# defends.p.p               = [   8.68,   11.21]
# attacks.p.n               = [  10.64,    8.40]
# defends.p.n               = [   8.19,   15.23]
# attacks.p.b               = [  10.28,   12.50]
# defends.p.b               = [   9.47,   10.94]
# attacks.p.r               = [  14.52,   11.58]
# defends.p.r               = [   7.76,    9.05]
# attacks.p.q               = [   8.42,   13.97]
# defends.p.q               = [   8.65,    8.79]
# attacks.p.k               = [   8.52,   12.53]
# defends.p.k               = [   8.98,   10.90]
# attacks.n.p               = [  -5.61,  -10.47]
# defends.n.p               = [  -0.24,   12.19]
# attacks.n.n               = [   8.36,    8.02]
# defends.n.n               = [   4.76,    4.81]
# attacks.n.b               = [  42.29,   42.49]
# defends.n.b               = [   5.67,    1.58]
# attacks.n.r               = [ 105.87,    6.41]
# defends.n.r               = [   8.00,   -3.61]
# attacks.n.q               = [  49.43,   -0.50]
# defends.n.q               = [   9.91,  -18.53]
# attacks.n.k               = [ 187.11,   -9.77]
# defends.n.k               = [   4.88,   -0.39]
# attacks.b.p               = [  -5.84,   -7.82]
# defends.b.p               = [   3.84,    2.11]
# attacks.b.n               = [  26.01,   29.04]
# defends.b.n               = [  11.25,   22.76]
# attacks.b.b               = [  10.61,   10.38]
# defends.b.b               = [  12.94,    7.63]
# attacks.b.r               = [  67.62,   -8.06]
# defends.b.r               = [   1.84,   18.60]
# attacks.b.q               = [  91.87,   11.12]
# defends.b.q               = [  15.07,    1.44]
# attacks.b.k               = [  91.04,   73.46]
# defends.b.k               = [   7.57,    2.30]
# attacks.r.p               = [ -11.63,    0.91]
# defends.r.p               = [  -9.15,    9.73]
# attacks.r.n               = [   3.06,   17.31]
# defends.r.n               = [   8.15,   19.15]
# attacks.r.b               = [  20.48,    5.23]
# defends.r.b               = [  12.57,   17.38]
# attacks.r.r               = [  11.14,   11.35]
# defends.r.r               = [   1.14,   13.71]
# attacks.r.q               = [  99.04,  -17.16]
# defends.r.q               = [  15.97,   24.39]
# attacks.r.k               = [ 268.09,  -25.06]
# defends.r.k               = [  11.53,   -6.96]
# attacks.q.p               = [  -0.74,   -8.18]
# defends.q.p               = [   2.72,   -0.02]
# attacks.q.n               = [   0.22,    2.63]
# defends.q.n               = [   9.58,   10.15]
# attacks.q.b               = [   1.41,   26.16]
# defends.q.b               = [   5.03,   16.53]
# attacks.q.r               = [  11.43,  -34.40]
# defends.q.r               = [   2.11,    8.43]
# attacks.q.q               = [  11.38,   10.63]
# defends.q.q               = [-239.84, -145.59]
# attacks.q.k               = [  97.67,  115.74]
# defends.q.k               = [  -4.67,  -24.98]
# attacks.k.p               = [  12.76,   15.32]
# defends.k.p               = [  12.74,   11.81]
# attacks.k.n               = [  11.42,   11.58]
# defends.k.n               = [  11.65,   11.75]
# attacks.k.b               = [  12.21,    8.58]
# defends.k.b               = [  12.68,    8.58]
# attacks.k.r               = [  11.11,   12.00]
# defends.k.r               = [  11.16,   12.59]
# attacks.k.q               = [  12.02,   11.71]
# defends.k.q               = [   9.32,   14.62]
# attacks.k.k               = [  11.86,   12.76]
# defends.k.k               = [  10.60,   0

[eval.mb]
enabled = false
filename = ""
consistency_report = true
consistency_adjust = true
internal_stats = false
draws_only = false
min_games = 50
max_pawns = 5
trade_factor = 2
p = [ 137.69,  140.12]
n = [ 625.46,  395.38]
b = [ 646.11,  415.35]
r = [ 848.05,  746.20]
q = [1845.37, 1374.29]
k = [   0.00,    0.00]


balances.NKk = 0
balances.BKk = 0


[eval.phaser]
enabled = true
method = "SO"
half_way_score = 3250



[qsearch]
enabled = true
only_on_capture = false
promos = false
ignore_see_fails = true
see_cutoff = 1
max_ply = 10
coarse_delta_prune = 1000
switches = 1279

[nmp]
enabled = true
recursive = true
successive = true
min_depth = 2
depth_reduction_strat = 100
a = 2.7
b = 0.198
c = 0.00017

[futility]
alpha_enabled = true
beta_enabled = false
prune_remaiking = false
avoid_checks = false
avoid_promos = false
promo_margin = false
max_depth = 2
max_depth_captures = 2
margin1 = 100
margin2 = 250
margin3 = 1500
eval_switches = 255
move_types_forbidden = 0

[pvs]
enabled = true
min_depth = 2

[extensions]
check_enabled = false
check_max_depth = 3
check_max_phase = 60
promo_enabled = false
promo_max_depth = 1
promo_rank = 7
promo_extend = 1

[lmr]
enabled = true
pv_node = true
only_nt_all = false
bad_captures = true
pawns = true
promos = false
killers = false
min_depth = 2
re_search = false
alpha_numeric = false
red_strat = 6

[mte]
branching_factor = 15
perc_of_time_adv = 100
moves_rem = 10
deterministic = false
nodestime = 0

[move_orderer]
enabled = true
prior_pv = true
prior_bm = false
tt_bm = true
mvv_lva = true
order = ["Start", "Hash", "Initialize", "GoodCaptureUpfrontSorted", "Killer", "Promo", "Quiet", "BadCapture", "End"]
qorder = ["Start", "Initialize", "Capture", "End"]

[repetition]
enabled = true
avoid_tt_on_repeats = false

[tt]
aging = true
probe_leaf_nodes = true
current_age = 10
enabled = true
use_tt_for_pv = false
allow_truncated_pv = false
allow_tt_at_root = false
mb = 8
hmvc_horizon = 85
min_ply = 1

[killers]
enabled = true
clear_every_move = false
use_ply_below = true

[history]
enabled = true
scale = 1
age_factor = 4

[explainer]
enabled = false

[restrictions]
enabled = true

[razor]
enabled = true
max_depth = 3
margin1 = 100
margin2 = 300
margin3 = 500
move_types_forbidden = 994


#end of file
