#
# Run: 68
# MSE improved from 0.063189 to 0.062911 (-0.44%)
# MSE improved from 0.063189 to 0.062914 (-0.43%) using integer weights
# Training file ../epd/quiet-labeled.epd
# Odonata odonata 0.3.48 built on Thu, 07 Oct 2021 16:34:16 +0000
# Path ../engines/odonata/odonata-stable
# Completed... 104.1 M position evaluations per second (6512 recalcs x 1417268 file lines)
# 

# baseline


# shared_tt = true
# thread_count = 1
# config_filename = "config.toml"
minmax = false

[ids]
enabled = true
part_ply = true
step_size = 1
start_ply = 1
end_ply = 127

[eval]
material = true
position = true
mobility = true
pawn = true
safety = true
contempt = true
tempo = true
phasing = true
mobility_phase_disable = 101
quantum = 1
min_depth_mob = 1
center_attacks = [1.0, 0.0]
undefended_sq = [4.0, 3.0]
undefended_piece = [-3.0, 49.0]
trapped_piece = [-17.0, -22.0]
partially_trapped_piece = [-7.0, -15.0]
defended_non_pawn = [0.0, 0.0]
xrayed = [0.0, 0.0]
pawn_doubled = [19.0, -35.0]
pawn_isolated = [-35.0, -5.0]
pawn_passed = [15.0, 28.0]
pawn_passed_r6 = [8.0, 94.0]
pawn_passed_r5 = [1.0, 50.0]
passers_on_rim = [-10.0, -10.0]
blockaded = [-10.0, -10.0]
blockaded_passers = [-10.0, -10.0]
bishop_pair = [62.0, 58.0]
fianchetto = [55.0, 27.0]
bishop_outposts = [0.0, 0.0]
bishop_color_pawns = [55.0, 27.0]
knight_forks = [0.0, 0.0]
knight_outposts = [0.0, 0.0]
rook_pair = [-1.0, -1.0]
doubled_rooks = [18.0, 48.0]
doubled_rooks_open_file = [17.0, 17.0]
rook_open_file = [59.0, -4.0]
queen_open_file = [-19.0, 37.0]
queen_early_develop = [0.0, 0.0]
pawn_adjacent_shield = [44.0, -15.0]
pawn_nearby_shield = [42.0, -14.0]
open_files_near_king = [-6.0, -1.0]
attacks_near_king = [-8.0, -2.0]
tropism_d1 = [-40.0, 29.0]
tropism_d2 = [-28.0, 11.0]
tropism_d3 = [-5.0, 2.0]
castling_rights = [0.0, 0.0]
contempt_penalty = [-30.0, 0.0]
tempo_bonus = [40.0, 50.0]

[eval.mb]
enabled = false
filename = ""
consistency_report = true
consistency_adjust = true
internal_stats = false
draws_only = false
min_games = 50
max_pawns = 5
trade_factor = 2
pawn = [100.0, 150.0]
knight = [632.0, 410.0]
bishop = [635.0, 429.0]
rook = [839.0, 771.0]
queen = [1822.0, 1405.0]

[qsearch]
enabled = true
only_on_capture = false
promos = false
ignore_see_fails = true
see_cutoff = 0
max_ply = 10
coarse_delta_prune = 1000
switches = 1279

[nmp]
enabled = true
recursive = true
successive = true
min_depth = 2
depth_reduction_strat = 100
a = 2.7
b = 0.198
c = 0.00017

[futility]
alpha_enabled = true
beta_enabled = false
prune_remaining = false
avoid_checks = false
avoid_promos = false
promo_margin = false
max_depth = 2
max_depth_captures = 2
margin1 = 100
margin2 = 250
margin3 = 1500
eval_switches = 255
move_types_forbidden = 0

[pvs]
enabled = true
min_depth = 2

[extensions]
check_enabled = false
check_max_depth = 3
check_max_phase = 60
promo_enabled = false
promo_max_depth = 1
promo_rank = 7
promo_extend = 1

[lmr]
enabled = true
pv_node = true
only_nt_all = false
bad_captures = true
pawns = true
promos = false
killers = false
min_depth = 2
re_search = false
alpha_numeric = false
red_strat = 6

[mte]
branching_factor = 15
perc_of_time_adv = 100
moves_rem = 10
deterministic = false
nodestime = 0

[move_orderer]
enabled = true
prior_pv = true
prior_bm = false
tt_bm = true
mvv_lva = true
order = ["Start", "Hash", "Initialize", "GoodCaptureUpfrontSorted", "Killer", "Promo", "Quiet", "BadCapture", "End"]
qorder = ["Start", "Initialize", "Capture", "End"]

[repetition]
enabled = true
avoid_tt_on_repeats = false

[tt]
aging = true
probe_leaf_nodes = true
current_age = 10
enabled = true
use_tt_for_pv = false
allow_truncated_pv = false
allow_tt_at_root = false
mb = 8
hmvc_horizon = 85
min_ply = 1

[killers]
enabled = true
clear_every_move = false
use_ply_below = true

[history]
enabled = true
scale = 1
age_factor = 4

[explainer]
enabled = false

[restrictions]
enabled = true

[razor]
enabled = true
max_depth = 3
margin1 = 100
margin2 = 300
margin3 = 500
move_types_forbidden = 994