[alias]
# benchmark = "t --cargo-profile=release --features=fast "
# benchmark_all = "t --cargo-profile=tournament --features=fast --no-capture bench_"
# benchmark = "t --cargo-profile=release --features=fast "
# benchmark_all = "t --cargo-profile=tournament --features=fast --no-capture bench_"
t = "nextest run"


# RUSTFLAGS="-C target-cpu=x86-64-v3" cargo t bench_   --no-capture 2>&1  | grep PROFD | sort


# [build]
# target = "x86_64-unknown-linux-musl"
# rustflags = ["-C","target-cpu=x86-64-v3"]
#rustflags = ["-C","target-cpu=generic"]

[target.x86_64-unknown-linux-musl]
rustflags = ["-C","target-cpu=x86-64-v3"]


[target.x86_64-unknown-linux-gnu]
rustflags = ["-C","target-cpu=x86-64-v3"]


