use std::marker::PhantomData;

use crate::weight::Number;
use crate::Feature;

pub(crate) struct RawHardcoded<T: Number> {
    _phantom: PhantomData<T>,
}






#[rustfmt::skip]
impl RawHardcoded<i32> {


    
    // VS Code regex
    //      // (.*) += \{ s = +(.*), e = +(.*) +\}
    //      ( $2, $3 ),  // $1

    // \( (.*)\..*, (.*)\..* \),  
    // ( $1, $2 ),
    pub const RAW_WTS: [(i32, i32); Feature::len() ] = {
        let a = &Self::RAW_WTS_MILLIS;
        let mut b = [(0_i32, 0_i32); Feature::len()];
        let mut i = 0;
        while i < b.len() {
            b[i] = (a[i].0 / 10, a[i].1 / 10);
            i += 1;
        }
        b
    };

    pub const RAW_WTS_MILLIS: [(i32, i32); Feature::len() ] = [
//
// type: (Millipawns) f64
//

(     -18,          -350 ),      //                    pawn_doubled      Pawns  
(       0,             0 ),      //           pawn_directly_doubled      Pawns  
(     -10,           235 ),      //                       pawn_weak      Pawns  
(    -105,            21 ),      //                   pawn_isolated      Pawns  
(      -0,           -54 ),      //         pawn_isolated_half_open      Pawns  
(       0,             0 ),      //                   semi_isolated      Pawns  
(    -129,           -89 ),      //                     pawn_passed      Pawns  
(     438,          5329 ),      //                  pawn_passed_r7      Pawns  
(     161,          3262 ),      //                  pawn_passed_r6      Pawns  
(     215,          1333 ),      //                  pawn_passed_r5      Pawns  
(    -204,           606 ),      //                  pawn_passed_r4      Pawns  
(     129,           146 ),      //                  passers_on_rim      Pawns  
(     253,          1149 ),      //           candidate_passed_pawn      Pawns  
(       0,            18 ),      //              blockaded_opponent      Pawns  
(       0,            18 ),      //                  blockaded_self      Pawns  
(    -160,          -143 ),      //                   blockaded_any      Pawns  
(     212,          -868 ),      //               blockaded_passers      Pawns  
(     468,          -184 ),      //             rooks_behind_passer      Pawns  
(     164,          -925 ),      //           pawn_isolated_doubled      Pawns  
(     252,            -0 ),      //             pawn_double_attacks      Pawns  
(       0,             0 ),      //                           space      Pawns  
(       0,             0 ),      //                    rammed_pawns      Pawns  
(      -1,          -131 ),      //      pawn_distant_neighbours_r7      Pawns  
(       0,          -199 ),      //      pawn_distant_neighbours_r6      Pawns  
(     189,          -244 ),      //      pawn_distant_neighbours_r5      Pawns  
(     228,           611 ),      //              pawn_connected_r67      Pawns  
(     278,           276 ),      //             pawn_connected_r345      Pawns  
(       0,             0 ),      //            passed_connected_r67      Pawns  
(       0,             0 ),      //           passed_connected_r345      Pawns  
(     692,          1037 ),      //                    pawn_duo_r67      Pawns  
(      71,           169 ),      //                  pawn_duo_r2345      Pawns  
(       0,             0 ),      //                  passed_duo_r67      Pawns  
(       0,             0 ),      //                passed_duo_r2345      Pawns  
(    -255,          -397 ),      //              backward_half_open      Pawns  
(     -45,          -169 ),      //                        backward      Pawns  
(       0,            -4 ),      //               potential_outpost  Imbalance  
(     236,          1097 ),      //                     bishop_pair  Imbalance  
(    1529,          -971 ),      //                       rook_pair  Imbalance  
(   10000,         10000 ),      //               certain_win_bonus  Imbalance  
(    3500,          6000 ),      //                       win_bonus  Imbalance  
(       0,             0 ),      //                      closedness   Mobility  
(      48,            81 ),      //                  center_attacks   Mobility  
(      35,           661 ),      //                  double_attacks   Mobility  
(       0,             0 ),      //                      controlled   Mobility  
(       0,             0 ),      //                        defended   Mobility  
(       0,             0 ),      //                        attacked   Mobility  
(       0,           -16 ),      //                   undefended_sq   Mobility  
(     -18,           366 ),      //                undefended_piece   Mobility  
(       0,             0 ),      //                     defends_own   Mobility  
(      -0,            -0 ),      //                   trapped_piece   Mobility  
(      -0,            -0 ),      //         partially_trapped_piece   Mobility  
(     638,            22 ),      //                  rook_open_file   Mobility  
(     226,           466 ),      //             rook_semi_open_file   Mobility  
(       0,            -0 ),      //                   knight_moves1   Mobility  
(    -251,          -410 ),      //                   knight_moves2   Mobility  
(     -57,          -169 ),      //                   knight_moves3   Mobility  
(     156,           172 ),      //                   knight_moves4   Mobility  
(     188,           540 ),      //                   knight_moves5   Mobility  
(     342,           554 ),      //                   knight_moves6   Mobility  
(      -0,            -0 ),      //                   bishop_moves1   Mobility  
(    -912,          -478 ),      //                   bishop_moves2   Mobility  
(      35,          -256 ),      //                   bishop_moves3   Mobility  
(     256,           282 ),      //                   bishop_moves4   Mobility  
(     328,           568 ),      //                   bishop_moves5   Mobility  
(     431,           511 ),      //                   bishop_moves6   Mobility  
(       0,            -0 ),      //                     rook_moves1   Mobility  
(       0,             1 ),      //                     rook_moves2   Mobility  
(     -10,          -206 ),      //                     rook_moves3   Mobility  
(      54,           225 ),      //                     rook_moves4   Mobility  
(      78,           458 ),      //                     rook_moves5   Mobility  
(     124,           592 ),      //                     rook_moves6   Mobility  
(       0,             0 ),      //                    queen_moves1   Mobility  
(       0,             0 ),      //                    queen_moves2   Mobility  
(     -17,            -0 ),      //                    queen_moves3   Mobility  
(     288,          -131 ),      //                    queen_moves4   Mobility  
(     320,           652 ),      //                    queen_moves5   Mobility  
(     288,           964 ),      //                    queen_moves6   Mobility  
(      -2,            29 ),      //               knight_closedness   Mobility  
(       0,             0 ),      //                  knight_outpost   Mobility  
(     139,           935 ),      //    knight_outpost_pawn_defended   Mobility  
(       0,             0 ),      //        knight_outpost_rook_safe   Mobility  
(      55,           123 ),      //                knight_connected   Mobility  
(     -37,            48 ),      //           knight_attacks_center   Mobility  
(       0,             0 ),      //                  knight_trapped   Mobility  
(      77,            89 ),      //                      fianchetto   Mobility  
(      -0,            -0 ),      //       discovered_atts_by_bishop   Mobility  
(      -0,            -0 ),      //         relative_pins_by_bishop   Mobility  
(     229,            31 ),      //                 bishop_outposts   Mobility  
(      10,           310 ),      //                bishop_connected   Mobility  
(     -16,           -34 ),      //              bishop_color_pawns   Mobility  
(    -186,           -86 ),      //                bishop_pawn_trap   Mobility  
(      58,          -186 ),      //       bishop_color_rammed_pawns   Mobility  
(       0,           336 ),      //                bishop_far_pawns   Mobility  
(       0,             0 ),      //                  bishop_trapped   Mobility  
(      -6,            14 ),      //               bishop_closedness   Mobility  
(       0,             0 ),      //           relative_pins_by_rook   Mobility  
(      -5,            16 ),      //                 rook_closedness   Mobility  
(     284,          -204 ),      //                   doubled_rooks   Mobility  
(       0,             0 ),      //                 connected_rooks   Mobility  
(      54,            29 ),      //         doubled_rooks_open_file   Mobility  
(    -258,           260 ),      //        enemy_pawns_on_rook_rank   Mobility  
(       0,             0 ),      //                    rook_trapped   Mobility  
(     -66,           184 ),      //             queen_early_develop   Mobility  
(    -239,           425 ),      //                 queen_open_file   Mobility  
(       0,             0 ),      //                   queen_trapped King Safety  
(     -30,            67 ),      //            pawn_adjacent_shield King Safety  
(     -13,           -90 ),      //              pawn_nearby_shield King Safety  
(    -302,           228 ),      //              pawn_shield_faulty King Safety  
(     194,           608 ),      //               king_safety_bonus King Safety  
(     108,           -80 ),      //                   storm_blocked King Safety  
(    -414,            47 ),      //                storm_blocked_r3 King Safety  
(      -0,            55 ),      //                storm_blocked_r4 King Safety  
(     -81,           102 ),      //                 storm_unblocked King Safety  
(    -511,          1193 ),      //             storm_unblocked_r23 King Safety  
(    -127,          -378 ),      //            open_files_near_king King Safety  
(    -223,           -52 ),      //        open_files_adjacent_king King Safety  
(       6,            21 ),      //               attacks_near_king King Safety  
(       0,             0 ),      //        double_attacks_near_king King Safety  
(       0,             0 ),      //                 moves_near_king King Safety  
(    -194,           440 ),      //                      tropism_d1 King Safety  
(    -188,           123 ),      //                      tropism_d2 King Safety  
(     -96,           -20 ),      //                      tropism_d3 King Safety  
(      -9,            16 ),      //                      tropism_d4 King Safety  
(     119,          -767 ),      //       king_trapped_on_back_rank King Safety  
(     -44,           -44 ),      //      rq_on_open_files_near_king King Safety  
(     511,          -328 ),      //           castling_rights_bonus King Safety  
(    -919,           340 ),      //                       uncastled King Safety  
(   -1627,          -733 ),      //                        checkers King Safety  
(     151,            -1 ),      //                pieces_near_king King Safety  
(     -86,            98 ),      //                pinned_near_king King Safety  
(    -266,          -230 ),      //                      pinned_far King Safety  
(   -1263,         -1490 ),      //               discovered_checks King Safety  
(     165,           251 ),      //                     tempo_bonus Initiative  
(     -14,          1534 ),      //              tempo_knight_forks Initiative  
(    -124,           -17 ),      //                    tempo_safety Initiative  
(       0,             0 ),      //          tempo_undefended_piece Initiative  
(      -0,             0 ),      //                contempt_penalty Initiative  
(      10,            10 ),      //                     win_metric1 Initiative  
(      10,            10 ),      //                     win_metric2 Initiative  
(       0,             0 ),      //                    new_feature1 Initiative  
(       0,             0 ),      //                    new_feature2 Initiative  
(       0,             0 ),      //                        pst_p_a1   Mobility  
(       0,             0 ),      //                        pst_p_b1   Mobility  
(       0,             0 ),      //                        pst_p_c1   Mobility  
(       0,             0 ),      //                        pst_p_d1   Mobility  
(       0,             0 ),      //                        pst_p_e1   Mobility  
(       0,             0 ),      //                        pst_p_f1   Mobility  
(       0,             0 ),      //                        pst_p_g1   Mobility  
(       0,             0 ),      //                        pst_p_h1   Mobility  
(      -0,           111 ),      //                        pst_p_a2   Mobility  
(     489,           483 ),      //                        pst_p_b2   Mobility  
(     -31,            55 ),      //                        pst_p_c2   Mobility  
(     270,          -579 ),      //                        pst_p_d2   Mobility  
(     115,            -3 ),      //                        pst_p_e2   Mobility  
(    -744,           358 ),      //                        pst_p_f2   Mobility  
(    -363,           436 ),      //                        pst_p_g2   Mobility  
(     -94,           525 ),      //                        pst_p_h2   Mobility  
(      37,           487 ),      //                        pst_p_a3   Mobility  
(     185,           307 ),      //                        pst_p_b3   Mobility  
(       0,            -9 ),      //                        pst_p_c3   Mobility  
(     387,          -861 ),      //                        pst_p_d3   Mobility  
(     -33,           -43 ),      //                        pst_p_e3   Mobility  
(     652,           114 ),      //                        pst_p_f3   Mobility  
(     349,           607 ),      //                        pst_p_g3   Mobility  
(    -393,           546 ),      //                        pst_p_h3   Mobility  
(       4,           392 ),      //                        pst_p_a4   Mobility  
(      75,           240 ),      //                        pst_p_b4   Mobility  
(     -10,             1 ),      //                        pst_p_c4   Mobility  
(      77,          -412 ),      //                        pst_p_d4   Mobility  
(      54,          -374 ),      //                        pst_p_e4   Mobility  
(     149,            44 ),      //                        pst_p_f4   Mobility  
(      -9,           172 ),      //                        pst_p_g4   Mobility  
(     174,            33 ),      //                        pst_p_h4   Mobility  
(    -108,           284 ),      //                        pst_p_a5   Mobility  
(     -65,            52 ),      //                        pst_p_b5   Mobility  
(      67,          -176 ),      //                        pst_p_c5   Mobility  
(     256,          -427 ),      //                        pst_p_d5   Mobility  
(     101,          -254 ),      //                        pst_p_e5   Mobility  
(     121,           -60 ),      //                        pst_p_f5   Mobility  
(    -104,           168 ),      //                        pst_p_g5   Mobility  
(    -274,           -36 ),      //                        pst_p_h5   Mobility  
(    -336,           -62 ),      //                        pst_p_a6   Mobility  
(    -275,            57 ),      //                        pst_p_b6   Mobility  
(     -27,          -236 ),      //                        pst_p_c6   Mobility  
(     -58,           -82 ),      //                        pst_p_d6   Mobility  
(     -11,           -41 ),      //                        pst_p_e6   Mobility  
(    -174,           172 ),      //                        pst_p_f6   Mobility  
(     169,          -111 ),      //                        pst_p_g6   Mobility  
(     -32,          -258 ),      //                        pst_p_h6   Mobility  
(    -183,            60 ),      //                        pst_p_a7   Mobility  
(    -110,           188 ),      //                        pst_p_b7   Mobility  
(     -81,          -171 ),      //                        pst_p_c7   Mobility  
(     -13,           -99 ),      //                        pst_p_d7   Mobility  
(     -58,           -62 ),      //                        pst_p_e7   Mobility  
(     442,            78 ),      //                        pst_p_f7   Mobility  
(     417,            23 ),      //                        pst_p_g7   Mobility  
(      29,          -477 ),      //                        pst_p_h7   Mobility  
(       0,             0 ),      //                        pst_p_a8   Mobility  
(       0,             0 ),      //                        pst_p_b8   Mobility  
(       0,             0 ),      //                        pst_p_c8   Mobility  
(       0,             0 ),      //                        pst_p_d8   Mobility  
(       0,             0 ),      //                        pst_p_e8   Mobility  
(       0,             0 ),      //                        pst_p_f8   Mobility  
(       0,             0 ),      //                        pst_p_g8   Mobility  
(       0,             0 ),      //                        pst_p_h8   Mobility  
(   -1686,            -0 ),      //                        pst_n_a1   Mobility  
(    -209,          -557 ),      //                        pst_n_b1   Mobility  
(      -0,             4 ),      //                        pst_n_c1   Mobility  
(     -47,             0 ),      //                        pst_n_d1   Mobility  
(      -0,             1 ),      //                        pst_n_e1   Mobility  
(   -1481,          -234 ),      //                        pst_n_f1   Mobility  
(       0,          -167 ),      //                        pst_n_g1   Mobility  
(    -766,          -353 ),      //                        pst_n_h1   Mobility  
(    -851,             2 ),      //                        pst_n_a2   Mobility  
(    -445,           232 ),      //                        pst_n_b2   Mobility  
(     593,          -123 ),      //                        pst_n_c2   Mobility  
(       1,             0 ),      //                        pst_n_d2   Mobility  
(     272,          -102 ),      //                        pst_n_e2   Mobility  
(      33,             0 ),      //                        pst_n_f2   Mobility  
(    -422,            -0 ),      //                        pst_n_g2   Mobility  
(    -277,          -409 ),      //                        pst_n_h2   Mobility  
(     178,            -4 ),      //                        pst_n_a3   Mobility  
(     175,            -3 ),      //                        pst_n_b3   Mobility  
(     203,           175 ),      //                        pst_n_c3   Mobility  
(     161,           260 ),      //                        pst_n_d3   Mobility  
(    1119,            70 ),      //                        pst_n_e3   Mobility  
(    -124,            93 ),      //                        pst_n_f3   Mobility  
(       3,             0 ),      //                        pst_n_g3   Mobility  
(    -434,           160 ),      //                        pst_n_h3   Mobility  
(     168,           208 ),      //                        pst_n_a4   Mobility  
(      31,           386 ),      //                        pst_n_b4   Mobility  
(     363,           260 ),      //                        pst_n_c4   Mobility  
(     485,           119 ),      //                        pst_n_d4   Mobility  
(      86,           226 ),      //                        pst_n_e4   Mobility  
(     198,           545 ),      //                        pst_n_f4   Mobility  
(    -154,             3 ),      //                        pst_n_g4   Mobility  
(     402,            -7 ),      //                        pst_n_h4   Mobility  
(     -54,          -256 ),      //                        pst_n_a5   Mobility  
(    -158,           328 ),      //                        pst_n_b5   Mobility  
(     310,           514 ),      //                        pst_n_c5   Mobility  
(     200,           528 ),      //                        pst_n_d5   Mobility  
(     261,           289 ),      //                        pst_n_e5   Mobility  
(     458,            19 ),      //                        pst_n_f5   Mobility  
(      15,           194 ),      //                        pst_n_g5   Mobility  
(     120,            -1 ),      //                        pst_n_h5   Mobility  
(    -285,          -234 ),      //                        pst_n_a6   Mobility  
(     308,           -46 ),      //                        pst_n_b6   Mobility  
(     180,            -5 ),      //                        pst_n_c6   Mobility  
(     399,           173 ),      //                        pst_n_d6   Mobility  
(     530,            98 ),      //                        pst_n_e6   Mobility  
(     222,           105 ),      //                        pst_n_f6   Mobility  
(     291,          -144 ),      //                        pst_n_g6   Mobility  
(    -155,            15 ),      //                        pst_n_h6   Mobility  
(      -0,          -111 ),      //                        pst_n_a7   Mobility  
(     -17,          -149 ),      //                        pst_n_b7   Mobility  
(    -163,            73 ),      //                        pst_n_c7   Mobility  
(      75,           -68 ),      //                        pst_n_d7   Mobility  
(      65,          -270 ),      //                        pst_n_e7   Mobility  
(      77,            -1 ),      //                        pst_n_f7   Mobility  
(     262,           586 ),      //                        pst_n_g7   Mobility  
(     214,             2 ),      //                        pst_n_h7   Mobility  
(    -382,            -1 ),      //                        pst_n_a8   Mobility  
(    -246,          -578 ),      //                        pst_n_b8   Mobility  
(     -57,            17 ),      //                        pst_n_c8   Mobility  
(    -275,           -96 ),      //                        pst_n_d8   Mobility  
(    -467,             5 ),      //                        pst_n_e8   Mobility  
(     -56,           102 ),      //                        pst_n_f8   Mobility  
(    -340,          -107 ),      //                        pst_n_g8   Mobility  
(    -299,             1 ),      //                        pst_n_h8   Mobility  
(       1,          -158 ),      //                        pst_b_a1   Mobility  
(       2,            -0 ),      //                        pst_b_b1   Mobility  
(       0,             2 ),      //                        pst_b_c1   Mobility  
(    -617,            -0 ),      //                        pst_b_d1   Mobility  
(    -789,           257 ),      //                        pst_b_e1   Mobility  
(    -733,             0 ),      //                        pst_b_f1   Mobility  
(    -278,            -4 ),      //                        pst_b_g1   Mobility  
(   -1044,            -0 ),      //                        pst_b_h1   Mobility  
(    -498,          -123 ),      //                        pst_b_a2   Mobility  
(      66,           -19 ),      //                        pst_b_b2   Mobility  
(    -288,            -0 ),      //                        pst_b_c2   Mobility  
(    -497,             0 ),      //                        pst_b_d2   Mobility  
(    -487,          -151 ),      //                        pst_b_e2   Mobility  
(    -415,            60 ),      //                        pst_b_f2   Mobility  
(    -548,           186 ),      //                        pst_b_g2   Mobility  
(   -1354,          -357 ),      //                        pst_b_h2   Mobility  
(       0,            91 ),      //                        pst_b_a3   Mobility  
(       3,           114 ),      //                        pst_b_b3   Mobility  
(     -31,           -85 ),      //                        pst_b_c3   Mobility  
(     299,           -16 ),      //                        pst_b_d3   Mobility  
(    -264,            -0 ),      //                        pst_b_e3   Mobility  
(     -11,           338 ),      //                        pst_b_f3   Mobility  
(    -421,           192 ),      //                        pst_b_g3   Mobility  
(    -321,           433 ),      //                        pst_b_h3   Mobility  
(      45,            -0 ),      //                        pst_b_a4   Mobility  
(    -234,            73 ),      //                        pst_b_b4   Mobility  
(     -67,           208 ),      //                        pst_b_c4   Mobility  
(     123,           363 ),      //                        pst_b_d4   Mobility  
(      -5,           487 ),      //                        pst_b_e4   Mobility  
(     -84,           147 ),      //                        pst_b_f4   Mobility  
(    -117,          -219 ),      //                        pst_b_g4   Mobility  
(    -308,             0 ),      //                        pst_b_h4   Mobility  
(     355,          -536 ),      //                        pst_b_a5   Mobility  
(     123,           -94 ),      //                        pst_b_b5   Mobility  
(     -20,            98 ),      //                        pst_b_c5   Mobility  
(     511,           294 ),      //                        pst_b_d5   Mobility  
(     402,           120 ),      //                        pst_b_e5   Mobility  
(     268,            75 ),      //                        pst_b_f5   Mobility  
(     206,            -0 ),      //                        pst_b_g5   Mobility  
(     318,          -347 ),      //                        pst_b_h5   Mobility  
(     107,            51 ),      //                        pst_b_a6   Mobility  
(     498,           -61 ),      //                        pst_b_b6   Mobility  
(     352,            71 ),      //                        pst_b_c6   Mobility  
(     237,            43 ),      //                        pst_b_d6   Mobility  
(     365,           299 ),      //                        pst_b_e6   Mobility  
(     315,            59 ),      //                        pst_b_f6   Mobility  
(     565,          -326 ),      //                        pst_b_g6   Mobility  
(     600,          -312 ),      //                        pst_b_h6   Mobility  
(    1023,            -3 ),      //                        pst_b_a7   Mobility  
(     246,          -273 ),      //                        pst_b_b7   Mobility  
(     208,            -0 ),      //                        pst_b_c7   Mobility  
(     202,           -21 ),      //                        pst_b_d7   Mobility  
(     126,           -70 ),      //                        pst_b_e7   Mobility  
(     500,            -2 ),      //                        pst_b_f7   Mobility  
(     361,             1 ),      //                        pst_b_g7   Mobility  
(     538,          -124 ),      //                        pst_b_h7   Mobility  
(    -384,            34 ),      //                        pst_b_a8   Mobility  
(      -0,          -341 ),      //                        pst_b_b8   Mobility  
(     159,          -144 ),      //                        pst_b_c8   Mobility  
(       1,          -116 ),      //                        pst_b_d8   Mobility  
(     548,            51 ),      //                        pst_b_e8   Mobility  
(     -61,          -387 ),      //                        pst_b_f8   Mobility  
(      -0,           176 ),      //                        pst_b_g8   Mobility  
(    -253,             0 ),      //                        pst_b_h8   Mobility  
(      57,           655 ),      //                        pst_r_a1   Mobility  
(      -4,           599 ),      //                        pst_r_b1   Mobility  
(      58,           387 ),      //                        pst_r_c1   Mobility  
(       7,           188 ),      //                        pst_r_d1   Mobility  
(     -41,           233 ),      //                        pst_r_e1   Mobility  
(     463,           244 ),      //                        pst_r_f1   Mobility  
(      -0,           304 ),      //                        pst_r_g1   Mobility  
(      -0,           694 ),      //                        pst_r_h1   Mobility  
(     406,           185 ),      //                        pst_r_a2   Mobility  
(     381,           469 ),      //                        pst_r_b2   Mobility  
(     551,           108 ),      //                        pst_r_c2   Mobility  
(     467,            80 ),      //                        pst_r_d2   Mobility  
(      72,           362 ),      //                        pst_r_e2   Mobility  
(     705,           129 ),      //                        pst_r_f2   Mobility  
(     342,           410 ),      //                        pst_r_g2   Mobility  
(     789,           293 ),      //                        pst_r_h2   Mobility  
(      11,           182 ),      //                        pst_r_a3   Mobility  
(     656,            17 ),      //                        pst_r_b3   Mobility  
(     309,             4 ),      //                        pst_r_c3   Mobility  
(      48,             3 ),      //                        pst_r_d3   Mobility  
(     -44,           -31 ),      //                        pst_r_e3   Mobility  
(     124,             8 ),      //                        pst_r_f3   Mobility  
(     426,            74 ),      //                        pst_r_g3   Mobility  
(      -0,            -2 ),      //                        pst_r_h3   Mobility  
(     -29,           185 ),      //                        pst_r_a4   Mobility  
(     -99,           101 ),      //                        pst_r_b4   Mobility  
(      80,             1 ),      //                        pst_r_c4   Mobility  
(    -231,            -3 ),      //                        pst_r_d4   Mobility  
(    -974,           409 ),      //                        pst_r_e4   Mobility  
(      -0,           -15 ),      //                        pst_r_f4   Mobility  
(      -0,            93 ),      //                        pst_r_g4   Mobility  
(       1,           -64 ),      //                        pst_r_h4   Mobility  
(    -149,             0 ),      //                        pst_r_a5   Mobility  
(     -82,           137 ),      //                        pst_r_b5   Mobility  
(    -497,            -4 ),      //                        pst_r_c5   Mobility  
(    -439,            -7 ),      //                        pst_r_d5   Mobility  
(    -221,          -266 ),      //                        pst_r_e5   Mobility  
(    -229,          -302 ),      //                        pst_r_f5   Mobility  
(     488,            -6 ),      //                        pst_r_g5   Mobility  
(     245,          -328 ),      //                        pst_r_h5   Mobility  
(     -81,          -152 ),      //                        pst_r_a6   Mobility  
(    -436,          -209 ),      //                        pst_r_b6   Mobility  
(    -701,           -94 ),      //                        pst_r_c6   Mobility  
(    -581,           -77 ),      //                        pst_r_d6   Mobility  
(     -64,          -124 ),      //                        pst_r_e6   Mobility  
(      -0,          -216 ),      //                        pst_r_f6   Mobility  
(     249,           -72 ),      //                        pst_r_g6   Mobility  
(       1,          -476 ),      //                        pst_r_h6   Mobility  
(    -204,           -60 ),      //                        pst_r_a7   Mobility  
(      95,          -487 ),      //                        pst_r_b7   Mobility  
(    -100,          -100 ),      //                        pst_r_c7   Mobility  
(    -142,          -136 ),      //                        pst_r_d7   Mobility  
(    -465,             0 ),      //                        pst_r_e7   Mobility  
(       7,          -451 ),      //                        pst_r_f7   Mobility  
(     206,          -317 ),      //                        pst_r_g7   Mobility  
(      -0,          -345 ),      //                        pst_r_h7   Mobility  
(    -152,           266 ),      //                        pst_r_a8   Mobility  
(     -47,            25 ),      //                        pst_r_b8   Mobility  
(    -194,           258 ),      //                        pst_r_c8   Mobility  
(    -207,           163 ),      //                        pst_r_d8   Mobility  
(       7,           -16 ),      //                        pst_r_e8   Mobility  
(      92,           -37 ),      //                        pst_r_f8   Mobility  
(     235,           -92 ),      //                        pst_r_g8   Mobility  
(     203,          -749 ),      //                        pst_r_h8   Mobility  
(    -440,          -143 ),      //                        pst_q_a1   Mobility  
(      33,           125 ),      //                        pst_q_b1   Mobility  
(    -354,           519 ),      //                        pst_q_c1   Mobility  
(       1,           267 ),      //                        pst_q_d1   Mobility  
(      17,            29 ),      //                        pst_q_e1   Mobility  
(       9,           388 ),      //                        pst_q_f1   Mobility  
(     106,           131 ),      //                        pst_q_g1   Mobility  
(     -88,           630 ),      //                        pst_q_h1   Mobility  
(    -277,           -16 ),      //                        pst_q_a2   Mobility  
(    -110,            59 ),      //                        pst_q_b2   Mobility  
(    -246,           380 ),      //                        pst_q_c2   Mobility  
(    -481,           430 ),      //                        pst_q_d2   Mobility  
(    -803,           647 ),      //                        pst_q_e2   Mobility  
(    -162,           817 ),      //                        pst_q_f2   Mobility  
(    -486,           736 ),      //                        pst_q_g2   Mobility  
(       0,             0 ),      //                        pst_q_h2   Mobility  
(      28,          -140 ),      //                        pst_q_a3   Mobility  
(      15,           -83 ),      //                        pst_q_b3   Mobility  
(    -111,           436 ),      //                        pst_q_c3   Mobility  
(      55,             1 ),      //                        pst_q_d3   Mobility  
(    -408,          1068 ),      //                        pst_q_e3   Mobility  
(      64,           121 ),      //                        pst_q_f3   Mobility  
(      83,           463 ),      //                        pst_q_g3   Mobility  
(    -349,           581 ),      //                        pst_q_h3   Mobility  
(      46,            44 ),      //                        pst_q_a4   Mobility  
(      63,            51 ),      //                        pst_q_b4   Mobility  
(     -30,           139 ),      //                        pst_q_c4   Mobility  
(    -381,           262 ),      //                        pst_q_d4   Mobility  
(    -349,            96 ),      //                        pst_q_e4   Mobility  
(    -121,           475 ),      //                        pst_q_f4   Mobility  
(    -322,           435 ),      //                        pst_q_g4   Mobility  
(    -216,           145 ),      //                        pst_q_h4   Mobility  
(     299,            -6 ),      //                        pst_q_a5   Mobility  
(     -39,           -37 ),      //                        pst_q_b5   Mobility  
(     156,           -71 ),      //                        pst_q_c5   Mobility  
(     -24,            -0 ),      //                        pst_q_d5   Mobility  
(      -5,           260 ),      //                        pst_q_e5   Mobility  
(     -21,            56 ),      //                        pst_q_f5   Mobility  
(     210,             0 ),      //                        pst_q_g5   Mobility  
(     206,            82 ),      //                        pst_q_h5   Mobility  
(     294,          -257 ),      //                        pst_q_a6   Mobility  
(     508,          -635 ),      //                        pst_q_b6   Mobility  
(     336,            -0 ),      //                        pst_q_c6   Mobility  
(     255,          -343 ),      //                        pst_q_d6   Mobility  
(      74,          -144 ),      //                        pst_q_e6   Mobility  
(     326,             0 ),      //                        pst_q_f6   Mobility  
(     171,           221 ),      //                        pst_q_g6   Mobility  
(       4,             0 ),      //                        pst_q_h6   Mobility  
(     186,            -0 ),      //                        pst_q_a7   Mobility  
(     317,            19 ),      //                        pst_q_b7   Mobility  
(     371,          -406 ),      //                        pst_q_c7   Mobility  
(     314,          -170 ),      //                        pst_q_d7   Mobility  
(     265,          -380 ),      //                        pst_q_e7   Mobility  
(     388,          -302 ),      //                        pst_q_f7   Mobility  
(     187,           -41 ),      //                        pst_q_g7   Mobility  
(     259,             0 ),      //                        pst_q_h7   Mobility  
(     245,            -4 ),      //                        pst_q_a8   Mobility  
(      75,          -335 ),      //                        pst_q_b8   Mobility  
(     202,            11 ),      //                        pst_q_c8   Mobility  
(     355,          -312 ),      //                        pst_q_d8   Mobility  
(      75,            34 ),      //                        pst_q_e8   Mobility  
(    -307,          -229 ),      //                        pst_q_f8   Mobility  
(      -2,           -44 ),      //                        pst_q_g8   Mobility  
(     -47,          -350 ),      //                        pst_q_h8   Mobility  
(      -1,          -402 ),      //                        pst_k_a1   Mobility  
(      -0,           -92 ),      //                        pst_k_b1   Mobility  
(       0,            -4 ),      //                        pst_k_c1   Mobility  
(       0,             1 ),      //                        pst_k_d1   Mobility  
(      -1,             1 ),      //                        pst_k_e1   Mobility  
(      -0,            -0 ),      //                        pst_k_f1   Mobility  
(       0,          -372 ),      //                        pst_k_g1   Mobility  
(       0,         -1198 ),      //                        pst_k_h1   Mobility  
(       0,             1 ),      //                        pst_k_a2   Mobility  
(     452,           474 ),      //                        pst_k_b2   Mobility  
(     744,           536 ),      //                        pst_k_c2   Mobility  
(     168,           259 ),      //                        pst_k_d2   Mobility  
(     321,           181 ),      //                        pst_k_e2   Mobility  
(    1400,           321 ),      //                        pst_k_f2   Mobility  
(       1,           495 ),      //                        pst_k_g2   Mobility  
(      -1,          -723 ),      //                        pst_k_h2   Mobility  
(      -1,          -238 ),      //                        pst_k_a3   Mobility  
(    1005,           524 ),      //                        pst_k_b3   Mobility  
(     356,           770 ),      //                        pst_k_c3   Mobility  
(    2040,           798 ),      //                        pst_k_d3   Mobility  
(      30,          1081 ),      //                        pst_k_e3   Mobility  
(    1910,           658 ),      //                        pst_k_f3   Mobility  
(      22,           572 ),      //                        pst_k_g3   Mobility  
(      -0,          -521 ),      //                        pst_k_h3   Mobility  
(      -0,          -788 ),      //                        pst_k_a4   Mobility  
(       0,           310 ),      //                        pst_k_b4   Mobility  
(     625,           630 ),      //                        pst_k_c4   Mobility  
(       0,           866 ),      //                        pst_k_d4   Mobility  
(      60,           959 ),      //                        pst_k_e4   Mobility  
(     335,           703 ),      //                        pst_k_f4   Mobility  
(       5,           230 ),      //                        pst_k_g4   Mobility  
(    -864,          -179 ),      //                        pst_k_h4   Mobility  
(      -0,          -687 ),      //                        pst_k_a5   Mobility  
(       0,           -57 ),      //                        pst_k_b5   Mobility  
(      -2,           623 ),      //                        pst_k_c5   Mobility  
(      -0,           726 ),      //                        pst_k_d5   Mobility  
(      32,           796 ),      //                        pst_k_e5   Mobility  
(       0,           502 ),      //                        pst_k_f5   Mobility  
(    -309,          -200 ),      //                        pst_k_g5   Mobility  
(   -1129,         -1044 ),      //                        pst_k_h5   Mobility  
(    -316,          -484 ),      //                        pst_k_a6   Mobility  
(    -187,          -278 ),      //                        pst_k_b6   Mobility  
(      10,           296 ),      //                        pst_k_c6   Mobility  
(    -892,           852 ),      //                        pst_k_d6   Mobility  
(    -869,           800 ),      //                        pst_k_e6   Mobility  
(      -4,           259 ),      //                        pst_k_f6   Mobility  
(      52,          -452 ),      //                        pst_k_g6   Mobility  
(    -566,         -1002 ),      //                        pst_k_h6   Mobility  
(    -101,          -354 ),      //                        pst_k_a7   Mobility  
(      -0,          -158 ),      //                        pst_k_b7   Mobility  
(    -444,           116 ),      //                        pst_k_c7   Mobility  
(    -543,           513 ),      //                        pst_k_d7   Mobility  
(    -405,           303 ),      //                        pst_k_e7   Mobility  
(     369,          -173 ),      //                        pst_k_f7   Mobility  
(     284,          -667 ),      //                        pst_k_g7   Mobility  
(     334,         -1337 ),      //                        pst_k_h7   Mobility  
(    -524,          -859 ),      //                        pst_k_a8   Mobility  
(      17,          -785 ),      //                        pst_k_b8   Mobility  
(    -246,          -376 ),      //                        pst_k_c8   Mobility  
(    -692,          -352 ),      //                        pst_k_d8   Mobility  
(    -451,          -415 ),      //                        pst_k_e8   Mobility  
(    -332,          -666 ),      //                        pst_k_f8   Mobility  
(     235,         -1228 ),      //                        pst_k_g8   Mobility  
(     298,         -2063 ),      //                        pst_k_h8   Mobility  
(    1000,          2228 ),      //                   material_pawn   Material  
(    5242,          5216 ),      //                 material_knight   Material  
(    5505,          5848 ),      //                 material_bishop   Material  
(    5609,         11232 ),      //                   material_rook   Material  
(   15404,         18727 ),      //                  material_queen   Material  
 ];
}

#[rustfmt::skip]
impl RawHardcoded<f32> {
    pub const RAW_WTS: [(f32, f32); Feature::len()] = [
//
// type: f64
//

(   -1.76,        -35.04 ),      //                    pawn_doubled      Pawns  
(    0.02,          0.02 ),      //           pawn_directly_doubled      Pawns  
(   -0.96,         23.46 ),      //                       pawn_weak      Pawns  
(  -10.52,          2.14 ),      //                   pawn_isolated      Pawns  
(   -0.03,         -5.41 ),      //         pawn_isolated_half_open      Pawns  
(    0.02,          0.02 ),      //                   semi_isolated      Pawns  
(  -12.90,         -8.88 ),      //                     pawn_passed      Pawns  
(   43.80,        532.94 ),      //                  pawn_passed_r7      Pawns  
(   16.10,        326.24 ),      //                  pawn_passed_r6      Pawns  
(   21.53,        133.30 ),      //                  pawn_passed_r5      Pawns  
(  -20.36,         60.60 ),      //                  pawn_passed_r4      Pawns  
(   12.95,         14.59 ),      //                  passers_on_rim      Pawns  
(   25.27,        114.94 ),      //           candidate_passed_pawn      Pawns  
(    0.02,          1.78 ),      //              blockaded_opponent      Pawns  
(    0.02,          1.78 ),      //                  blockaded_self      Pawns  
(  -16.04,        -14.28 ),      //                   blockaded_any      Pawns  
(   21.22,        -86.82 ),      //               blockaded_passers      Pawns  
(   46.83,        -18.37 ),      //             rooks_behind_passer      Pawns  
(   16.35,        -92.49 ),      //           pawn_isolated_doubled      Pawns  
(   25.24,         -0.04 ),      //             pawn_double_attacks      Pawns  
(    0.02,          0.02 ),      //                           space      Pawns  
(    0.02,          0.02 ),      //                    rammed_pawns      Pawns  
(   -0.08,        -13.10 ),      //      pawn_distant_neighbours_r7      Pawns  
(    0.04,        -19.87 ),      //      pawn_distant_neighbours_r6      Pawns  
(   18.93,        -24.39 ),      //      pawn_distant_neighbours_r5      Pawns  
(   22.79,         61.08 ),      //              pawn_connected_r67      Pawns  
(   27.75,         27.61 ),      //             pawn_connected_r345      Pawns  
(    0.02,          0.02 ),      //            passed_connected_r67      Pawns  
(    0.02,          0.02 ),      //           passed_connected_r345      Pawns  
(   69.19,        103.74 ),      //                    pawn_duo_r67      Pawns  
(    7.12,         16.85 ),      //                  pawn_duo_r2345      Pawns  
(    0.02,          0.02 ),      //                  passed_duo_r67      Pawns  
(    0.02,          0.02 ),      //                passed_duo_r2345      Pawns  
(  -25.45,        -39.66 ),      //              backward_half_open      Pawns  
(   -4.54,        -16.93 ),      //                        backward      Pawns  
(    0.02,         -0.43 ),      //               potential_outpost  Imbalance  
(   23.59,        109.67 ),      //                     bishop_pair  Imbalance  
(  152.87,        -97.11 ),      //                       rook_pair  Imbalance  
( 1000.00,       1000.00 ),      //               certain_win_bonus  Imbalance  
(  350.00,        600.00 ),      //                       win_bonus  Imbalance  
(    0.02,          0.02 ),      //                      closedness   Mobility  
(    4.78,          8.07 ),      //                  center_attacks   Mobility  
(    3.50,         66.14 ),      //                  double_attacks   Mobility  
(    0.02,          0.02 ),      //                      controlled   Mobility  
(    0.02,          0.02 ),      //                        defended   Mobility  
(    0.02,          0.02 ),      //                        attacked   Mobility  
(    0.03,         -1.63 ),      //                   undefended_sq   Mobility  
(   -1.77,         36.64 ),      //                undefended_piece   Mobility  
(    0.02,          0.02 ),      //                     defends_own   Mobility  
(   -0.02,         -0.02 ),      //                   trapped_piece   Mobility  
(   -0.02,         -0.02 ),      //         partially_trapped_piece   Mobility  
(   63.75,          2.21 ),      //                  rook_open_file   Mobility  
(   22.62,         46.63 ),      //             rook_semi_open_file   Mobility  
(    0.02,         -0.01 ),      //                   knight_moves1   Mobility  
(  -25.13,        -40.98 ),      //                   knight_moves2   Mobility  
(   -5.65,        -16.92 ),      //                   knight_moves3   Mobility  
(   15.63,         17.25 ),      //                   knight_moves4   Mobility  
(   18.80,         53.99 ),      //                   knight_moves5   Mobility  
(   34.19,         55.40 ),      //                   knight_moves6   Mobility  
(   -0.03,         -0.00 ),      //                   bishop_moves1   Mobility  
(  -91.24,        -47.78 ),      //                   bishop_moves2   Mobility  
(    3.53,        -25.56 ),      //                   bishop_moves3   Mobility  
(   25.59,         28.18 ),      //                   bishop_moves4   Mobility  
(   32.79,         56.77 ),      //                   bishop_moves5   Mobility  
(   43.11,         51.07 ),      //                   bishop_moves6   Mobility  
(    0.01,         -0.03 ),      //                     rook_moves1   Mobility  
(    0.00,          0.09 ),      //                     rook_moves2   Mobility  
(   -1.04,        -20.57 ),      //                     rook_moves3   Mobility  
(    5.42,         22.52 ),      //                     rook_moves4   Mobility  
(    7.83,         45.79 ),      //                     rook_moves5   Mobility  
(   12.42,         59.19 ),      //                     rook_moves6   Mobility  
(    0.02,          0.02 ),      //                    queen_moves1   Mobility  
(    0.02,          0.02 ),      //                    queen_moves2   Mobility  
(   -1.67,         -0.03 ),      //                    queen_moves3   Mobility  
(   28.82,        -13.13 ),      //                    queen_moves4   Mobility  
(   32.01,         65.25 ),      //                    queen_moves5   Mobility  
(   28.76,         96.45 ),      //                    queen_moves6   Mobility  
(   -0.21,          2.86 ),      //               knight_closedness   Mobility  
(    0.02,          0.02 ),      //                  knight_outpost   Mobility  
(   13.95,         93.46 ),      //    knight_outpost_pawn_defended   Mobility  
(    0.02,          0.02 ),      //        knight_outpost_rook_safe   Mobility  
(    5.52,         12.29 ),      //                knight_connected   Mobility  
(   -3.70,          4.84 ),      //           knight_attacks_center   Mobility  
(    0.02,          0.02 ),      //                  knight_trapped   Mobility  
(    7.71,          8.87 ),      //                      fianchetto   Mobility  
(   -0.02,         -0.02 ),      //       discovered_atts_by_bishop   Mobility  
(   -0.02,         -0.02 ),      //         relative_pins_by_bishop   Mobility  
(   22.86,          3.10 ),      //                 bishop_outposts   Mobility  
(    0.96,         31.04 ),      //                bishop_connected   Mobility  
(   -1.58,         -3.43 ),      //              bishop_color_pawns   Mobility  
(  -18.60,         -8.61 ),      //                bishop_pawn_trap   Mobility  
(    5.82,        -18.60 ),      //       bishop_color_rammed_pawns   Mobility  
(    0.01,         33.59 ),      //                bishop_far_pawns   Mobility  
(    0.02,          0.02 ),      //                  bishop_trapped   Mobility  
(   -0.65,          1.36 ),      //               bishop_closedness   Mobility  
(    0.00,          0.00 ),      //           relative_pins_by_rook   Mobility  
(   -0.46,          1.63 ),      //                 rook_closedness   Mobility  
(   28.35,        -20.39 ),      //                   doubled_rooks   Mobility  
(    0.02,          0.02 ),      //                 connected_rooks   Mobility  
(    5.42,          2.93 ),      //         doubled_rooks_open_file   Mobility  
(  -25.81,         26.01 ),      //        enemy_pawns_on_rook_rank   Mobility  
(    0.02,          0.02 ),      //                    rook_trapped   Mobility  
(   -6.63,         18.41 ),      //             queen_early_develop   Mobility  
(  -23.85,         42.54 ),      //                 queen_open_file   Mobility  
(    0.02,          0.02 ),      //                   queen_trapped King Safety  
(   -3.01,          6.70 ),      //            pawn_adjacent_shield King Safety  
(   -1.26,         -9.01 ),      //              pawn_nearby_shield King Safety  
(  -30.20,         22.77 ),      //              pawn_shield_faulty King Safety  
(   19.44,         60.76 ),      //               king_safety_bonus King Safety  
(   10.78,         -8.01 ),      //                   storm_blocked King Safety  
(  -41.41,          4.72 ),      //                storm_blocked_r3 King Safety  
(   -0.01,          5.46 ),      //                storm_blocked_r4 King Safety  
(   -8.08,         10.23 ),      //                 storm_unblocked King Safety  
(  -51.12,        119.29 ),      //             storm_unblocked_r23 King Safety  
(  -12.68,        -37.81 ),      //            open_files_near_king King Safety  
(  -22.34,         -5.23 ),      //        open_files_adjacent_king King Safety  
(    0.59,          2.10 ),      //               attacks_near_king King Safety  
(    0.02,          0.02 ),      //        double_attacks_near_king King Safety  
(    0.02,          0.02 ),      //                 moves_near_king King Safety  
(  -19.41,         44.05 ),      //                      tropism_d1 King Safety  
(  -18.78,         12.29 ),      //                      tropism_d2 King Safety  
(   -9.65,         -2.00 ),      //                      tropism_d3 King Safety  
(   -0.94,          1.57 ),      //                      tropism_d4 King Safety  
(   11.95,        -76.65 ),      //       king_trapped_on_back_rank King Safety  
(   -4.43,         -4.40 ),      //      rq_on_open_files_near_king King Safety  
(   51.12,        -32.83 ),      //           castling_rights_bonus King Safety  
(  -91.93,         33.95 ),      //                       uncastled King Safety  
( -162.73,        -73.28 ),      //                        checkers King Safety  
(   15.12,         -0.10 ),      //                pieces_near_king King Safety  
(   -8.57,          9.82 ),      //                pinned_near_king King Safety  
(  -26.62,        -22.98 ),      //                      pinned_far King Safety  
( -126.27,       -149.01 ),      //               discovered_checks King Safety  
(   16.48,         25.15 ),      //                     tempo_bonus Initiative  
(   -1.35,        153.36 ),      //              tempo_knight_forks Initiative  
(  -12.41,         -1.74 ),      //                    tempo_safety Initiative  
(    0.02,          0.02 ),      //          tempo_undefended_piece Initiative  
(   -0.01,          0.02 ),      //                contempt_penalty Initiative  
(    1.00,          1.00 ),      //                     win_metric1 Initiative  
(    1.00,          1.00 ),      //                     win_metric2 Initiative  
(     0.0,           0.0 ),      //                    new_feature1 Initiative  
(     0.0,           0.0 ),      //                    new_feature2 Initiative  
(    0.02,          0.02 ),      //                        pst_p_a1   Mobility  
(    0.02,          0.02 ),      //                        pst_p_b1   Mobility  
(    0.02,          0.02 ),      //                        pst_p_c1   Mobility  
(    0.02,          0.02 ),      //                        pst_p_d1   Mobility  
(    0.02,          0.02 ),      //                        pst_p_e1   Mobility  
(    0.02,          0.02 ),      //                        pst_p_f1   Mobility  
(    0.02,          0.02 ),      //                        pst_p_g1   Mobility  
(    0.02,          0.02 ),      //                        pst_p_h1   Mobility  
(   -0.04,         11.09 ),      //                        pst_p_a2   Mobility  
(   48.86,         48.29 ),      //                        pst_p_b2   Mobility  
(   -3.07,          5.53 ),      //                        pst_p_c2   Mobility  
(   27.05,        -57.88 ),      //                        pst_p_d2   Mobility  
(   11.51,         -0.27 ),      //                        pst_p_e2   Mobility  
(  -74.37,         35.84 ),      //                        pst_p_f2   Mobility  
(  -36.32,         43.62 ),      //                        pst_p_g2   Mobility  
(   -9.36,         52.51 ),      //                        pst_p_h2   Mobility  
(    3.71,         48.67 ),      //                        pst_p_a3   Mobility  
(   18.48,         30.70 ),      //                        pst_p_b3   Mobility  
(    0.00,         -0.90 ),      //                        pst_p_c3   Mobility  
(   38.67,        -86.09 ),      //                        pst_p_d3   Mobility  
(   -3.31,         -4.29 ),      //                        pst_p_e3   Mobility  
(   65.21,         11.42 ),      //                        pst_p_f3   Mobility  
(   34.94,         60.71 ),      //                        pst_p_g3   Mobility  
(  -39.35,         54.57 ),      //                        pst_p_h3   Mobility  
(    0.44,         39.25 ),      //                        pst_p_a4   Mobility  
(    7.49,         24.00 ),      //                        pst_p_b4   Mobility  
(   -1.05,          0.14 ),      //                        pst_p_c4   Mobility  
(    7.74,        -41.25 ),      //                        pst_p_d4   Mobility  
(    5.41,        -37.43 ),      //                        pst_p_e4   Mobility  
(   14.88,          4.44 ),      //                        pst_p_f4   Mobility  
(   -0.89,         17.17 ),      //                        pst_p_g4   Mobility  
(   17.41,          3.30 ),      //                        pst_p_h4   Mobility  
(  -10.79,         28.43 ),      //                        pst_p_a5   Mobility  
(   -6.51,          5.19 ),      //                        pst_p_b5   Mobility  
(    6.70,        -17.58 ),      //                        pst_p_c5   Mobility  
(   25.64,        -42.73 ),      //                        pst_p_d5   Mobility  
(   10.11,        -25.43 ),      //                        pst_p_e5   Mobility  
(   12.10,         -6.04 ),      //                        pst_p_f5   Mobility  
(  -10.42,         16.79 ),      //                        pst_p_g5   Mobility  
(  -27.44,         -3.62 ),      //                        pst_p_h5   Mobility  
(  -33.64,         -6.17 ),      //                        pst_p_a6   Mobility  
(  -27.46,          5.70 ),      //                        pst_p_b6   Mobility  
(   -2.72,        -23.59 ),      //                        pst_p_c6   Mobility  
(   -5.81,         -8.20 ),      //                        pst_p_d6   Mobility  
(   -1.09,         -4.11 ),      //                        pst_p_e6   Mobility  
(  -17.36,         17.25 ),      //                        pst_p_f6   Mobility  
(   16.90,        -11.07 ),      //                        pst_p_g6   Mobility  
(   -3.24,        -25.82 ),      //                        pst_p_h6   Mobility  
(  -18.33,          5.96 ),      //                        pst_p_a7   Mobility  
(  -11.02,         18.75 ),      //                        pst_p_b7   Mobility  
(   -8.07,        -17.15 ),      //                        pst_p_c7   Mobility  
(   -1.26,         -9.90 ),      //                        pst_p_d7   Mobility  
(   -5.85,         -6.22 ),      //                        pst_p_e7   Mobility  
(   44.22,          7.78 ),      //                        pst_p_f7   Mobility  
(   41.65,          2.28 ),      //                        pst_p_g7   Mobility  
(    2.91,        -47.74 ),      //                        pst_p_h7   Mobility  
(    0.02,          0.02 ),      //                        pst_p_a8   Mobility  
(    0.02,          0.02 ),      //                        pst_p_b8   Mobility  
(    0.02,          0.02 ),      //                        pst_p_c8   Mobility  
(    0.02,          0.02 ),      //                        pst_p_d8   Mobility  
(    0.02,          0.02 ),      //                        pst_p_e8   Mobility  
(    0.02,          0.02 ),      //                        pst_p_f8   Mobility  
(    0.02,          0.02 ),      //                        pst_p_g8   Mobility  
(    0.02,          0.02 ),      //                        pst_p_h8   Mobility  
( -168.64,         -0.00 ),      //                        pst_n_a1   Mobility  
(  -20.90,        -55.74 ),      //                        pst_n_b1   Mobility  
(   -0.03,          0.39 ),      //                        pst_n_c1   Mobility  
(   -4.71,          0.03 ),      //                        pst_n_d1   Mobility  
(   -0.03,          0.12 ),      //                        pst_n_e1   Mobility  
( -148.15,        -23.43 ),      //                        pst_n_f1   Mobility  
(    0.03,        -16.68 ),      //                        pst_n_g1   Mobility  
(  -76.62,        -35.34 ),      //                        pst_n_h1   Mobility  
(  -85.07,          0.16 ),      //                        pst_n_a2   Mobility  
(  -44.54,         23.19 ),      //                        pst_n_b2   Mobility  
(   59.34,        -12.31 ),      //                        pst_n_c2   Mobility  
(    0.05,          0.03 ),      //                        pst_n_d2   Mobility  
(   27.24,        -10.19 ),      //                        pst_n_e2   Mobility  
(    3.31,          0.00 ),      //                        pst_n_f2   Mobility  
(  -42.15,         -0.03 ),      //                        pst_n_g2   Mobility  
(  -27.67,        -40.86 ),      //                        pst_n_h2   Mobility  
(   17.76,         -0.36 ),      //                        pst_n_a3   Mobility  
(   17.55,         -0.26 ),      //                        pst_n_b3   Mobility  
(   20.30,         17.51 ),      //                        pst_n_c3   Mobility  
(   16.08,         26.05 ),      //                        pst_n_d3   Mobility  
(  111.91,          7.01 ),      //                        pst_n_e3   Mobility  
(  -12.37,          9.29 ),      //                        pst_n_f3   Mobility  
(    0.33,          0.02 ),      //                        pst_n_g3   Mobility  
(  -43.37,         15.99 ),      //                        pst_n_h3   Mobility  
(   16.78,         20.84 ),      //                        pst_n_a4   Mobility  
(    3.12,         38.62 ),      //                        pst_n_b4   Mobility  
(   36.27,         26.00 ),      //                        pst_n_c4   Mobility  
(   48.45,         11.93 ),      //                        pst_n_d4   Mobility  
(    8.57,         22.59 ),      //                        pst_n_e4   Mobility  
(   19.81,         54.53 ),      //                        pst_n_f4   Mobility  
(  -15.37,          0.35 ),      //                        pst_n_g4   Mobility  
(   40.18,         -0.66 ),      //                        pst_n_h4   Mobility  
(   -5.41,        -25.64 ),      //                        pst_n_a5   Mobility  
(  -15.76,         32.80 ),      //                        pst_n_b5   Mobility  
(   31.00,         51.36 ),      //                        pst_n_c5   Mobility  
(   19.98,         52.81 ),      //                        pst_n_d5   Mobility  
(   26.15,         28.92 ),      //                        pst_n_e5   Mobility  
(   45.78,          1.93 ),      //                        pst_n_f5   Mobility  
(    1.53,         19.37 ),      //                        pst_n_g5   Mobility  
(   12.04,         -0.05 ),      //                        pst_n_h5   Mobility  
(  -28.53,        -23.41 ),      //                        pst_n_a6   Mobility  
(   30.77,         -4.55 ),      //                        pst_n_b6   Mobility  
(   17.98,         -0.48 ),      //                        pst_n_c6   Mobility  
(   39.93,         17.28 ),      //                        pst_n_d6   Mobility  
(   53.04,          9.83 ),      //                        pst_n_e6   Mobility  
(   22.24,         10.50 ),      //                        pst_n_f6   Mobility  
(   29.12,        -14.37 ),      //                        pst_n_g6   Mobility  
(  -15.49,          1.54 ),      //                        pst_n_h6   Mobility  
(   -0.01,        -11.09 ),      //                        pst_n_a7   Mobility  
(   -1.74,        -14.86 ),      //                        pst_n_b7   Mobility  
(  -16.26,          7.28 ),      //                        pst_n_c7   Mobility  
(    7.52,         -6.78 ),      //                        pst_n_d7   Mobility  
(    6.49,        -27.05 ),      //                        pst_n_e7   Mobility  
(    7.67,         -0.08 ),      //                        pst_n_f7   Mobility  
(   26.18,         58.62 ),      //                        pst_n_g7   Mobility  
(   21.42,          0.18 ),      //                        pst_n_h7   Mobility  
(  -38.24,         -0.07 ),      //                        pst_n_a8   Mobility  
(  -24.61,        -57.76 ),      //                        pst_n_b8   Mobility  
(   -5.66,          1.74 ),      //                        pst_n_c8   Mobility  
(  -27.46,         -9.57 ),      //                        pst_n_d8   Mobility  
(  -46.70,          0.53 ),      //                        pst_n_e8   Mobility  
(   -5.55,         10.24 ),      //                        pst_n_f8   Mobility  
(  -33.99,        -10.72 ),      //                        pst_n_g8   Mobility  
(  -29.91,          0.06 ),      //                        pst_n_h8   Mobility  
(    0.12,        -15.77 ),      //                        pst_b_a1   Mobility  
(    0.16,         -0.00 ),      //                        pst_b_b1   Mobility  
(    0.01,          0.21 ),      //                        pst_b_c1   Mobility  
(  -61.74,         -0.01 ),      //                        pst_b_d1   Mobility  
(  -78.94,         25.72 ),      //                        pst_b_e1   Mobility  
(  -73.33,          0.03 ),      //                        pst_b_f1   Mobility  
(  -27.83,         -0.40 ),      //                        pst_b_g1   Mobility  
( -104.43,         -0.00 ),      //                        pst_b_h1   Mobility  
(  -49.77,        -12.28 ),      //                        pst_b_a2   Mobility  
(    6.55,         -1.90 ),      //                        pst_b_b2   Mobility  
(  -28.84,         -0.03 ),      //                        pst_b_c2   Mobility  
(  -49.70,          0.02 ),      //                        pst_b_d2   Mobility  
(  -48.72,        -15.06 ),      //                        pst_b_e2   Mobility  
(  -41.46,          6.03 ),      //                        pst_b_f2   Mobility  
(  -54.81,         18.56 ),      //                        pst_b_g2   Mobility  
( -135.40,        -35.73 ),      //                        pst_b_h2   Mobility  
(    0.01,          9.07 ),      //                        pst_b_a3   Mobility  
(    0.30,         11.44 ),      //                        pst_b_b3   Mobility  
(   -3.11,         -8.51 ),      //                        pst_b_c3   Mobility  
(   29.90,         -1.57 ),      //                        pst_b_d3   Mobility  
(  -26.36,         -0.00 ),      //                        pst_b_e3   Mobility  
(   -1.09,         33.78 ),      //                        pst_b_f3   Mobility  
(  -42.12,         19.19 ),      //                        pst_b_g3   Mobility  
(  -32.08,         43.26 ),      //                        pst_b_h3   Mobility  
(    4.50,         -0.03 ),      //                        pst_b_a4   Mobility  
(  -23.36,          7.28 ),      //                        pst_b_b4   Mobility  
(   -6.70,         20.78 ),      //                        pst_b_c4   Mobility  
(   12.33,         36.33 ),      //                        pst_b_d4   Mobility  
(   -0.51,         48.70 ),      //                        pst_b_e4   Mobility  
(   -8.35,         14.69 ),      //                        pst_b_f4   Mobility  
(  -11.73,        -21.93 ),      //                        pst_b_g4   Mobility  
(  -30.75,          0.03 ),      //                        pst_b_h4   Mobility  
(   35.48,        -53.56 ),      //                        pst_b_a5   Mobility  
(   12.28,         -9.38 ),      //                        pst_b_b5   Mobility  
(   -2.01,          9.77 ),      //                        pst_b_c5   Mobility  
(   51.07,         29.37 ),      //                        pst_b_d5   Mobility  
(   40.16,         12.03 ),      //                        pst_b_e5   Mobility  
(   26.84,          7.51 ),      //                        pst_b_f5   Mobility  
(   20.58,         -0.02 ),      //                        pst_b_g5   Mobility  
(   31.81,        -34.69 ),      //                        pst_b_h5   Mobility  
(   10.66,          5.09 ),      //                        pst_b_a6   Mobility  
(   49.78,         -6.08 ),      //                        pst_b_b6   Mobility  
(   35.16,          7.13 ),      //                        pst_b_c6   Mobility  
(   23.66,          4.32 ),      //                        pst_b_d6   Mobility  
(   36.51,         29.93 ),      //                        pst_b_e6   Mobility  
(   31.55,          5.91 ),      //                        pst_b_f6   Mobility  
(   56.52,        -32.59 ),      //                        pst_b_g6   Mobility  
(   60.00,        -31.18 ),      //                        pst_b_h6   Mobility  
(  102.29,         -0.30 ),      //                        pst_b_a7   Mobility  
(   24.56,        -27.30 ),      //                        pst_b_b7   Mobility  
(   20.82,         -0.00 ),      //                        pst_b_c7   Mobility  
(   20.25,         -2.10 ),      //                        pst_b_d7   Mobility  
(   12.58,         -7.01 ),      //                        pst_b_e7   Mobility  
(   50.02,         -0.17 ),      //                        pst_b_f7   Mobility  
(   36.06,          0.06 ),      //                        pst_b_g7   Mobility  
(   53.77,        -12.44 ),      //                        pst_b_h7   Mobility  
(  -38.36,          3.38 ),      //                        pst_b_a8   Mobility  
(   -0.03,        -34.07 ),      //                        pst_b_b8   Mobility  
(   15.95,        -14.35 ),      //                        pst_b_c8   Mobility  
(    0.09,        -11.63 ),      //                        pst_b_d8   Mobility  
(   54.82,          5.08 ),      //                        pst_b_e8   Mobility  
(   -6.05,        -38.74 ),      //                        pst_b_f8   Mobility  
(   -0.04,         17.57 ),      //                        pst_b_g8   Mobility  
(  -25.30,          0.04 ),      //                        pst_b_h8   Mobility  
(    5.67,         65.47 ),      //                        pst_r_a1   Mobility  
(   -0.36,         59.86 ),      //                        pst_r_b1   Mobility  
(    5.83,         38.74 ),      //                        pst_r_c1   Mobility  
(    0.66,         18.76 ),      //                        pst_r_d1   Mobility  
(   -4.07,         23.29 ),      //                        pst_r_e1   Mobility  
(   46.34,         24.43 ),      //                        pst_r_f1   Mobility  
(   -0.02,         30.42 ),      //                        pst_r_g1   Mobility  
(   -0.03,         69.41 ),      //                        pst_r_h1   Mobility  
(   40.63,         18.48 ),      //                        pst_r_a2   Mobility  
(   38.12,         46.86 ),      //                        pst_r_b2   Mobility  
(   55.06,         10.82 ),      //                        pst_r_c2   Mobility  
(   46.66,          7.97 ),      //                        pst_r_d2   Mobility  
(    7.25,         36.19 ),      //                        pst_r_e2   Mobility  
(   70.50,         12.87 ),      //                        pst_r_f2   Mobility  
(   34.22,         41.04 ),      //                        pst_r_g2   Mobility  
(   78.93,         29.34 ),      //                        pst_r_h2   Mobility  
(    1.06,         18.21 ),      //                        pst_r_a3   Mobility  
(   65.62,          1.70 ),      //                        pst_r_b3   Mobility  
(   30.86,          0.36 ),      //                        pst_r_c3   Mobility  
(    4.81,          0.32 ),      //                        pst_r_d3   Mobility  
(   -4.36,         -3.06 ),      //                        pst_r_e3   Mobility  
(   12.39,          0.75 ),      //                        pst_r_f3   Mobility  
(   42.62,          7.39 ),      //                        pst_r_g3   Mobility  
(   -0.01,         -0.21 ),      //                        pst_r_h3   Mobility  
(   -2.86,         18.45 ),      //                        pst_r_a4   Mobility  
(   -9.92,         10.10 ),      //                        pst_r_b4   Mobility  
(    8.04,          0.05 ),      //                        pst_r_c4   Mobility  
(  -23.12,         -0.28 ),      //                        pst_r_d4   Mobility  
(  -97.39,         40.93 ),      //                        pst_r_e4   Mobility  
(   -0.00,         -1.51 ),      //                        pst_r_f4   Mobility  
(   -0.02,          9.27 ),      //                        pst_r_g4   Mobility  
(    0.12,         -6.44 ),      //                        pst_r_h4   Mobility  
(  -14.93,          0.04 ),      //                        pst_r_a5   Mobility  
(   -8.18,         13.69 ),      //                        pst_r_b5   Mobility  
(  -49.73,         -0.39 ),      //                        pst_r_c5   Mobility  
(  -43.92,         -0.69 ),      //                        pst_r_d5   Mobility  
(  -22.15,        -26.57 ),      //                        pst_r_e5   Mobility  
(  -22.85,        -30.21 ),      //                        pst_r_f5   Mobility  
(   48.78,         -0.59 ),      //                        pst_r_g5   Mobility  
(   24.54,        -32.85 ),      //                        pst_r_h5   Mobility  
(   -8.06,        -15.22 ),      //                        pst_r_a6   Mobility  
(  -43.60,        -20.93 ),      //                        pst_r_b6   Mobility  
(  -70.12,         -9.43 ),      //                        pst_r_c6   Mobility  
(  -58.10,         -7.73 ),      //                        pst_r_d6   Mobility  
(   -6.45,        -12.36 ),      //                        pst_r_e6   Mobility  
(   -0.01,        -21.62 ),      //                        pst_r_f6   Mobility  
(   24.90,         -7.23 ),      //                        pst_r_g6   Mobility  
(    0.09,        -47.56 ),      //                        pst_r_h6   Mobility  
(  -20.43,         -5.99 ),      //                        pst_r_a7   Mobility  
(    9.49,        -48.67 ),      //                        pst_r_b7   Mobility  
(  -10.00,        -10.04 ),      //                        pst_r_c7   Mobility  
(  -14.22,        -13.58 ),      //                        pst_r_d7   Mobility  
(  -46.53,          0.00 ),      //                        pst_r_e7   Mobility  
(    0.72,        -45.07 ),      //                        pst_r_f7   Mobility  
(   20.56,        -31.73 ),      //                        pst_r_g7   Mobility  
(   -0.00,        -34.54 ),      //                        pst_r_h7   Mobility  
(  -15.17,         26.63 ),      //                        pst_r_a8   Mobility  
(   -4.65,          2.48 ),      //                        pst_r_b8   Mobility  
(  -19.44,         25.78 ),      //                        pst_r_c8   Mobility  
(  -20.71,         16.28 ),      //                        pst_r_d8   Mobility  
(    0.70,         -1.61 ),      //                        pst_r_e8   Mobility  
(    9.21,         -3.71 ),      //                        pst_r_f8   Mobility  
(   23.53,         -9.23 ),      //                        pst_r_g8   Mobility  
(   20.33,        -74.88 ),      //                        pst_r_h8   Mobility  
(  -43.98,        -14.29 ),      //                        pst_q_a1   Mobility  
(    3.31,         12.47 ),      //                        pst_q_b1   Mobility  
(  -35.44,         51.90 ),      //                        pst_q_c1   Mobility  
(    0.05,         26.74 ),      //                        pst_q_d1   Mobility  
(    1.73,          2.88 ),      //                        pst_q_e1   Mobility  
(    0.90,         38.76 ),      //                        pst_q_f1   Mobility  
(   10.65,         13.13 ),      //                        pst_q_g1   Mobility  
(   -8.82,         62.99 ),      //                        pst_q_h1   Mobility  
(  -27.71,         -1.59 ),      //                        pst_q_a2   Mobility  
(  -10.98,          5.90 ),      //                        pst_q_b2   Mobility  
(  -24.58,         38.01 ),      //                        pst_q_c2   Mobility  
(  -48.07,         43.03 ),      //                        pst_q_d2   Mobility  
(  -80.35,         64.74 ),      //                        pst_q_e2   Mobility  
(  -16.16,         81.70 ),      //                        pst_q_f2   Mobility  
(  -48.63,         73.56 ),      //                        pst_q_g2   Mobility  
(    0.03,          0.03 ),      //                        pst_q_h2   Mobility  
(    2.83,        -14.04 ),      //                        pst_q_a3   Mobility  
(    1.46,         -8.30 ),      //                        pst_q_b3   Mobility  
(  -11.06,         43.60 ),      //                        pst_q_c3   Mobility  
(    5.50,          0.06 ),      //                        pst_q_d3   Mobility  
(  -40.82,        106.83 ),      //                        pst_q_e3   Mobility  
(    6.44,         12.11 ),      //                        pst_q_f3   Mobility  
(    8.32,         46.30 ),      //                        pst_q_g3   Mobility  
(  -34.94,         58.12 ),      //                        pst_q_h3   Mobility  
(    4.64,          4.37 ),      //                        pst_q_a4   Mobility  
(    6.29,          5.08 ),      //                        pst_q_b4   Mobility  
(   -3.04,         13.87 ),      //                        pst_q_c4   Mobility  
(  -38.09,         26.17 ),      //                        pst_q_d4   Mobility  
(  -34.91,          9.58 ),      //                        pst_q_e4   Mobility  
(  -12.12,         47.47 ),      //                        pst_q_f4   Mobility  
(  -32.16,         43.53 ),      //                        pst_q_g4   Mobility  
(  -21.63,         14.54 ),      //                        pst_q_h4   Mobility  
(   29.94,         -0.63 ),      //                        pst_q_a5   Mobility  
(   -3.91,         -3.71 ),      //                        pst_q_b5   Mobility  
(   15.65,         -7.10 ),      //                        pst_q_c5   Mobility  
(   -2.39,         -0.00 ),      //                        pst_q_d5   Mobility  
(   -0.46,         25.99 ),      //                        pst_q_e5   Mobility  
(   -2.07,          5.59 ),      //                        pst_q_f5   Mobility  
(   21.05,          0.00 ),      //                        pst_q_g5   Mobility  
(   20.58,          8.16 ),      //                        pst_q_h5   Mobility  
(   29.38,        -25.70 ),      //                        pst_q_a6   Mobility  
(   50.82,        -63.49 ),      //                        pst_q_b6   Mobility  
(   33.57,         -0.04 ),      //                        pst_q_c6   Mobility  
(   25.45,        -34.31 ),      //                        pst_q_d6   Mobility  
(    7.38,        -14.44 ),      //                        pst_q_e6   Mobility  
(   32.60,          0.02 ),      //                        pst_q_f6   Mobility  
(   17.07,         22.11 ),      //                        pst_q_g6   Mobility  
(    0.40,          0.04 ),      //                        pst_q_h6   Mobility  
(   18.64,         -0.02 ),      //                        pst_q_a7   Mobility  
(   31.70,          1.90 ),      //                        pst_q_b7   Mobility  
(   37.06,        -40.59 ),      //                        pst_q_c7   Mobility  
(   31.38,        -16.99 ),      //                        pst_q_d7   Mobility  
(   26.53,        -38.03 ),      //                        pst_q_e7   Mobility  
(   38.78,        -30.22 ),      //                        pst_q_f7   Mobility  
(   18.71,         -4.08 ),      //                        pst_q_g7   Mobility  
(   25.93,          0.00 ),      //                        pst_q_h7   Mobility  
(   24.51,         -0.42 ),      //                        pst_q_a8   Mobility  
(    7.46,        -33.53 ),      //                        pst_q_b8   Mobility  
(   20.16,          1.15 ),      //                        pst_q_c8   Mobility  
(   35.53,        -31.17 ),      //                        pst_q_d8   Mobility  
(    7.54,          3.42 ),      //                        pst_q_e8   Mobility  
(  -30.74,        -22.93 ),      //                        pst_q_f8   Mobility  
(   -0.18,         -4.45 ),      //                        pst_q_g8   Mobility  
(   -4.70,        -34.98 ),      //                        pst_q_h8   Mobility  
(   -0.06,        -40.25 ),      //                        pst_k_a1   Mobility  
(   -0.02,         -9.25 ),      //                        pst_k_b1   Mobility  
(    0.01,         -0.43 ),      //                        pst_k_c1   Mobility  
(    0.02,          0.12 ),      //                        pst_k_d1   Mobility  
(   -0.07,          0.05 ),      //                        pst_k_e1   Mobility  
(   -0.02,         -0.01 ),      //                        pst_k_f1   Mobility  
(    0.02,        -37.22 ),      //                        pst_k_g1   Mobility  
(    0.01,       -119.83 ),      //                        pst_k_h1   Mobility  
(    0.01,          0.11 ),      //                        pst_k_a2   Mobility  
(   45.20,         47.37 ),      //                        pst_k_b2   Mobility  
(   74.41,         53.61 ),      //                        pst_k_c2   Mobility  
(   16.82,         25.93 ),      //                        pst_k_d2   Mobility  
(   32.07,         18.10 ),      //                        pst_k_e2   Mobility  
(  139.96,         32.07 ),      //                        pst_k_f2   Mobility  
(    0.09,         49.49 ),      //                        pst_k_g2   Mobility  
(   -0.05,        -72.33 ),      //                        pst_k_h2   Mobility  
(   -0.10,        -23.81 ),      //                        pst_k_a3   Mobility  
(  100.52,         52.41 ),      //                        pst_k_b3   Mobility  
(   35.61,         76.99 ),      //                        pst_k_c3   Mobility  
(  203.99,         79.75 ),      //                        pst_k_d3   Mobility  
(    2.98,        108.07 ),      //                        pst_k_e3   Mobility  
(  190.98,         65.83 ),      //                        pst_k_f3   Mobility  
(    2.23,         57.18 ),      //                        pst_k_g3   Mobility  
(   -0.00,        -52.13 ),      //                        pst_k_h3   Mobility  
(   -0.03,        -78.82 ),      //                        pst_k_a4   Mobility  
(    0.00,         30.98 ),      //                        pst_k_b4   Mobility  
(   62.47,         62.99 ),      //                        pst_k_c4   Mobility  
(    0.00,         86.57 ),      //                        pst_k_d4   Mobility  
(    6.01,         95.93 ),      //                        pst_k_e4   Mobility  
(   33.54,         70.28 ),      //                        pst_k_f4   Mobility  
(    0.51,         23.05 ),      //                        pst_k_g4   Mobility  
(  -86.37,        -17.87 ),      //                        pst_k_h4   Mobility  
(   -0.01,        -68.70 ),      //                        pst_k_a5   Mobility  
(    0.01,         -5.72 ),      //                        pst_k_b5   Mobility  
(   -0.20,         62.30 ),      //                        pst_k_c5   Mobility  
(   -0.01,         72.63 ),      //                        pst_k_d5   Mobility  
(    3.22,         79.63 ),      //                        pst_k_e5   Mobility  
(    0.01,         50.20 ),      //                        pst_k_f5   Mobility  
(  -30.88,        -19.96 ),      //                        pst_k_g5   Mobility  
( -112.86,       -104.45 ),      //                        pst_k_h5   Mobility  
(  -31.57,        -48.38 ),      //                        pst_k_a6   Mobility  
(  -18.70,        -27.80 ),      //                        pst_k_b6   Mobility  
(    1.01,         29.62 ),      //                        pst_k_c6   Mobility  
(  -89.24,         85.21 ),      //                        pst_k_d6   Mobility  
(  -86.91,         80.03 ),      //                        pst_k_e6   Mobility  
(   -0.43,         25.85 ),      //                        pst_k_f6   Mobility  
(    5.25,        -45.24 ),      //                        pst_k_g6   Mobility  
(  -56.61,       -100.20 ),      //                        pst_k_h6   Mobility  
(  -10.06,        -35.44 ),      //                        pst_k_a7   Mobility  
(   -0.01,        -15.83 ),      //                        pst_k_b7   Mobility  
(  -44.43,         11.65 ),      //                        pst_k_c7   Mobility  
(  -54.31,         51.28 ),      //                        pst_k_d7   Mobility  
(  -40.50,         30.33 ),      //                        pst_k_e7   Mobility  
(   36.92,        -17.30 ),      //                        pst_k_f7   Mobility  
(   28.35,        -66.66 ),      //                        pst_k_g7   Mobility  
(   33.41,       -133.66 ),      //                        pst_k_h7   Mobility  
(  -52.44,        -85.86 ),      //                        pst_k_a8   Mobility  
(    1.70,        -78.50 ),      //                        pst_k_b8   Mobility  
(  -24.65,        -37.58 ),      //                        pst_k_c8   Mobility  
(  -69.15,        -35.19 ),      //                        pst_k_d8   Mobility  
(  -45.06,        -41.51 ),      //                        pst_k_e8   Mobility  
(  -33.23,        -66.59 ),      //                        pst_k_f8   Mobility  
(   23.45,       -122.77 ),      //                        pst_k_g8   Mobility  
(   29.78,       -206.28 ),      //                        pst_k_h8   Mobility  
(  100.00,        222.83 ),      //                   material_pawn   Material  
(  524.20,        521.56 ),      //                 material_knight   Material  
(  550.55,        584.84 ),      //                 material_bishop   Material  
(  560.88,       1123.18 ),      //                   material_rook   Material  
( 1540.45,       1872.69 ),      //                  material_queen   Material  
    

    ];
}

